// Code generated by ent, DO NOT EDIT.

package attemptanswer

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the attemptanswer type in the database.
	Label = "attempt_answer"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// EdgeAttempt holds the string denoting the attempt edge name in mutations.
	EdgeAttempt = "attempt"
	// EdgeQuestion holds the string denoting the question edge name in mutations.
	EdgeQuestion = "question"
	// EdgeAnswer holds the string denoting the answer edge name in mutations.
	EdgeAnswer = "answer"
	// Table holds the table name of the attemptanswer in the database.
	Table = "attempt_answers"
	// AttemptTable is the table that holds the attempt relation/edge.
	AttemptTable = "attempt_answers"
	// AttemptInverseTable is the table name for the Attempt entity.
	// It exists in this package in order to avoid circular dependency with the "attempt" package.
	AttemptInverseTable = "attempts"
	// AttemptColumn is the table column denoting the attempt relation/edge.
	AttemptColumn = "attempt_attempt_answers"
	// QuestionTable is the table that holds the question relation/edge.
	QuestionTable = "attempt_answers"
	// QuestionInverseTable is the table name for the Question entity.
	// It exists in this package in order to avoid circular dependency with the "question" package.
	QuestionInverseTable = "questions"
	// QuestionColumn is the table column denoting the question relation/edge.
	QuestionColumn = "question_attempt_answers"
	// AnswerTable is the table that holds the answer relation/edge.
	AnswerTable = "attempt_answers"
	// AnswerInverseTable is the table name for the Answer entity.
	// It exists in this package in order to avoid circular dependency with the "answer" package.
	AnswerInverseTable = "answers"
	// AnswerColumn is the table column denoting the answer relation/edge.
	AnswerColumn = "answer_attempt_answers"
)

// Columns holds all SQL columns for attemptanswer fields.
var Columns = []string{
	FieldID,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "attempt_answers"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"answer_attempt_answers",
	"attempt_attempt_answers",
	"question_attempt_answers",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the AttemptAnswer queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByAttemptField orders the results by attempt field.
func ByAttemptField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAttemptStep(), sql.OrderByField(field, opts...))
	}
}

// ByQuestionField orders the results by question field.
func ByQuestionField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newQuestionStep(), sql.OrderByField(field, opts...))
	}
}

// ByAnswerField orders the results by answer field.
func ByAnswerField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAnswerStep(), sql.OrderByField(field, opts...))
	}
}
func newAttemptStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AttemptInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, AttemptTable, AttemptColumn),
	)
}
func newQuestionStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(QuestionInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, QuestionTable, QuestionColumn),
	)
}
func newAnswerStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AnswerInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, AnswerTable, AnswerColumn),
	)
}
