// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AnswersColumns holds the columns for the "answers" table.
	AnswersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "text", Type: field.TypeString},
		{Name: "is_correct", Type: field.TypeBool, Default: false},
		{Name: "order_index", Type: field.TypeInt, Default: 0},
		{Name: "question_answers", Type: field.TypeUUID, Nullable: true},
	}
	// AnswersTable holds the schema information for the "answers" table.
	AnswersTable = &schema.Table{
		Name:       "answers",
		Columns:    AnswersColumns,
		PrimaryKey: []*schema.Column{AnswersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "answers_questions_answers",
				Columns:    []*schema.Column{AnswersColumns[4]},
				RefColumns: []*schema.Column{QuestionsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// AttemptsColumns holds the columns for the "attempts" table.
	AttemptsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "score", Type: field.TypeInt},
		{Name: "total", Type: field.TypeInt},
		{Name: "created_at", Type: field.TypeTime, Nullable: true},
		{Name: "quiz_attempts", Type: field.TypeUUID, Nullable: true},
		{Name: "user_attempts", Type: field.TypeUUID, Nullable: true},
	}
	// AttemptsTable holds the schema information for the "attempts" table.
	AttemptsTable = &schema.Table{
		Name:       "attempts",
		Columns:    AttemptsColumns,
		PrimaryKey: []*schema.Column{AttemptsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "attempts_quizs_attempts",
				Columns:    []*schema.Column{AttemptsColumns[4]},
				RefColumns: []*schema.Column{QuizsColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "attempts_users_attempts",
				Columns:    []*schema.Column{AttemptsColumns[5]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// AttemptAnswersColumns holds the columns for the "attempt_answers" table.
	AttemptAnswersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "answer_attempt_answers", Type: field.TypeUUID, Nullable: true},
		{Name: "attempt_attempt_answers", Type: field.TypeUUID, Nullable: true},
		{Name: "question_attempt_answers", Type: field.TypeUUID, Nullable: true},
	}
	// AttemptAnswersTable holds the schema information for the "attempt_answers" table.
	AttemptAnswersTable = &schema.Table{
		Name:       "attempt_answers",
		Columns:    AttemptAnswersColumns,
		PrimaryKey: []*schema.Column{AttemptAnswersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "attempt_answers_answers_attempt_answers",
				Columns:    []*schema.Column{AttemptAnswersColumns[1]},
				RefColumns: []*schema.Column{AnswersColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "attempt_answers_attempts_attempt_answers",
				Columns:    []*schema.Column{AttemptAnswersColumns[2]},
				RefColumns: []*schema.Column{AttemptsColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "attempt_answers_questions_attempt_answers",
				Columns:    []*schema.Column{AttemptAnswersColumns[3]},
				RefColumns: []*schema.Column{QuestionsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// QuestionsColumns holds the columns for the "questions" table.
	QuestionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "text", Type: field.TypeString},
		{Name: "order_index", Type: field.TypeInt, Default: 0},
		{Name: "quiz_questions", Type: field.TypeUUID, Nullable: true},
	}
	// QuestionsTable holds the schema information for the "questions" table.
	QuestionsTable = &schema.Table{
		Name:       "questions",
		Columns:    QuestionsColumns,
		PrimaryKey: []*schema.Column{QuestionsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "questions_quizs_questions",
				Columns:    []*schema.Column{QuestionsColumns[3]},
				RefColumns: []*schema.Column{QuizsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// QuizsColumns holds the columns for the "quizs" table.
	QuizsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "title", Type: field.TypeString},
		{Name: "is_published", Type: field.TypeBool, Default: false},
		{Name: "pass_threshold", Type: field.TypeInt, Default: 0},
		{Name: "one_attempt", Type: field.TypeBool, Default: false},
		{Name: "show_answers", Type: field.TypeBool, Default: false},
		{Name: "created_at", Type: field.TypeTime, Nullable: true},
		{Name: "user_quizzes", Type: field.TypeUUID, Nullable: true},
	}
	// QuizsTable holds the schema information for the "quizs" table.
	QuizsTable = &schema.Table{
		Name:       "quizs",
		Columns:    QuizsColumns,
		PrimaryKey: []*schema.Column{QuizsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "quizs_users_quizzes",
				Columns:    []*schema.Column{QuizsColumns[7]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "email", Type: field.TypeString, Unique: true},
		{Name: "password_hash", Type: field.TypeString},
		{Name: "role", Type: field.TypeString, Default: "user"},
		{Name: "created_at", Type: field.TypeTime, Nullable: true},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AnswersTable,
		AttemptsTable,
		AttemptAnswersTable,
		QuestionsTable,
		QuizsTable,
		UsersTable,
	}
)

func init() {
	AnswersTable.ForeignKeys[0].RefTable = QuestionsTable
	AttemptsTable.ForeignKeys[0].RefTable = QuizsTable
	AttemptsTable.ForeignKeys[1].RefTable = UsersTable
	AttemptAnswersTable.ForeignKeys[0].RefTable = AnswersTable
	AttemptAnswersTable.ForeignKeys[1].RefTable = AttemptsTable
	AttemptAnswersTable.ForeignKeys[2].RefTable = QuestionsTable
	QuestionsTable.ForeignKeys[0].RefTable = QuizsTable
	QuizsTable.ForeignKeys[0].RefTable = UsersTable
}
