// Code generated by ent, DO NOT EDIT.

package quiz

import (
	"time"

	"encore.app/ent/predicate"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Quiz {
	return predicate.Quiz(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Quiz {
	return predicate.Quiz(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Quiz {
	return predicate.Quiz(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Quiz {
	return predicate.Quiz(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Quiz {
	return predicate.Quiz(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Quiz {
	return predicate.Quiz(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Quiz {
	return predicate.Quiz(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Quiz {
	return predicate.Quiz(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Quiz {
	return predicate.Quiz(sql.FieldLTE(FieldID, id))
}

// Title applies equality check predicate on the "title" field. It's identical to TitleEQ.
func Title(v string) predicate.Quiz {
	return predicate.Quiz(sql.FieldEQ(FieldTitle, v))
}

// IsPublished applies equality check predicate on the "is_published" field. It's identical to IsPublishedEQ.
func IsPublished(v bool) predicate.Quiz {
	return predicate.Quiz(sql.FieldEQ(FieldIsPublished, v))
}

// PassThreshold applies equality check predicate on the "pass_threshold" field. It's identical to PassThresholdEQ.
func PassThreshold(v int) predicate.Quiz {
	return predicate.Quiz(sql.FieldEQ(FieldPassThreshold, v))
}

// OneAttempt applies equality check predicate on the "one_attempt" field. It's identical to OneAttemptEQ.
func OneAttempt(v bool) predicate.Quiz {
	return predicate.Quiz(sql.FieldEQ(FieldOneAttempt, v))
}

// ShowAnswers applies equality check predicate on the "show_answers" field. It's identical to ShowAnswersEQ.
func ShowAnswers(v bool) predicate.Quiz {
	return predicate.Quiz(sql.FieldEQ(FieldShowAnswers, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Quiz {
	return predicate.Quiz(sql.FieldEQ(FieldCreatedAt, v))
}

// TitleEQ applies the EQ predicate on the "title" field.
func TitleEQ(v string) predicate.Quiz {
	return predicate.Quiz(sql.FieldEQ(FieldTitle, v))
}

// TitleNEQ applies the NEQ predicate on the "title" field.
func TitleNEQ(v string) predicate.Quiz {
	return predicate.Quiz(sql.FieldNEQ(FieldTitle, v))
}

// TitleIn applies the In predicate on the "title" field.
func TitleIn(vs ...string) predicate.Quiz {
	return predicate.Quiz(sql.FieldIn(FieldTitle, vs...))
}

// TitleNotIn applies the NotIn predicate on the "title" field.
func TitleNotIn(vs ...string) predicate.Quiz {
	return predicate.Quiz(sql.FieldNotIn(FieldTitle, vs...))
}

// TitleGT applies the GT predicate on the "title" field.
func TitleGT(v string) predicate.Quiz {
	return predicate.Quiz(sql.FieldGT(FieldTitle, v))
}

// TitleGTE applies the GTE predicate on the "title" field.
func TitleGTE(v string) predicate.Quiz {
	return predicate.Quiz(sql.FieldGTE(FieldTitle, v))
}

// TitleLT applies the LT predicate on the "title" field.
func TitleLT(v string) predicate.Quiz {
	return predicate.Quiz(sql.FieldLT(FieldTitle, v))
}

// TitleLTE applies the LTE predicate on the "title" field.
func TitleLTE(v string) predicate.Quiz {
	return predicate.Quiz(sql.FieldLTE(FieldTitle, v))
}

// TitleContains applies the Contains predicate on the "title" field.
func TitleContains(v string) predicate.Quiz {
	return predicate.Quiz(sql.FieldContains(FieldTitle, v))
}

// TitleHasPrefix applies the HasPrefix predicate on the "title" field.
func TitleHasPrefix(v string) predicate.Quiz {
	return predicate.Quiz(sql.FieldHasPrefix(FieldTitle, v))
}

// TitleHasSuffix applies the HasSuffix predicate on the "title" field.
func TitleHasSuffix(v string) predicate.Quiz {
	return predicate.Quiz(sql.FieldHasSuffix(FieldTitle, v))
}

// TitleEqualFold applies the EqualFold predicate on the "title" field.
func TitleEqualFold(v string) predicate.Quiz {
	return predicate.Quiz(sql.FieldEqualFold(FieldTitle, v))
}

// TitleContainsFold applies the ContainsFold predicate on the "title" field.
func TitleContainsFold(v string) predicate.Quiz {
	return predicate.Quiz(sql.FieldContainsFold(FieldTitle, v))
}

// IsPublishedEQ applies the EQ predicate on the "is_published" field.
func IsPublishedEQ(v bool) predicate.Quiz {
	return predicate.Quiz(sql.FieldEQ(FieldIsPublished, v))
}

// IsPublishedNEQ applies the NEQ predicate on the "is_published" field.
func IsPublishedNEQ(v bool) predicate.Quiz {
	return predicate.Quiz(sql.FieldNEQ(FieldIsPublished, v))
}

// PassThresholdEQ applies the EQ predicate on the "pass_threshold" field.
func PassThresholdEQ(v int) predicate.Quiz {
	return predicate.Quiz(sql.FieldEQ(FieldPassThreshold, v))
}

// PassThresholdNEQ applies the NEQ predicate on the "pass_threshold" field.
func PassThresholdNEQ(v int) predicate.Quiz {
	return predicate.Quiz(sql.FieldNEQ(FieldPassThreshold, v))
}

// PassThresholdIn applies the In predicate on the "pass_threshold" field.
func PassThresholdIn(vs ...int) predicate.Quiz {
	return predicate.Quiz(sql.FieldIn(FieldPassThreshold, vs...))
}

// PassThresholdNotIn applies the NotIn predicate on the "pass_threshold" field.
func PassThresholdNotIn(vs ...int) predicate.Quiz {
	return predicate.Quiz(sql.FieldNotIn(FieldPassThreshold, vs...))
}

// PassThresholdGT applies the GT predicate on the "pass_threshold" field.
func PassThresholdGT(v int) predicate.Quiz {
	return predicate.Quiz(sql.FieldGT(FieldPassThreshold, v))
}

// PassThresholdGTE applies the GTE predicate on the "pass_threshold" field.
func PassThresholdGTE(v int) predicate.Quiz {
	return predicate.Quiz(sql.FieldGTE(FieldPassThreshold, v))
}

// PassThresholdLT applies the LT predicate on the "pass_threshold" field.
func PassThresholdLT(v int) predicate.Quiz {
	return predicate.Quiz(sql.FieldLT(FieldPassThreshold, v))
}

// PassThresholdLTE applies the LTE predicate on the "pass_threshold" field.
func PassThresholdLTE(v int) predicate.Quiz {
	return predicate.Quiz(sql.FieldLTE(FieldPassThreshold, v))
}

// OneAttemptEQ applies the EQ predicate on the "one_attempt" field.
func OneAttemptEQ(v bool) predicate.Quiz {
	return predicate.Quiz(sql.FieldEQ(FieldOneAttempt, v))
}

// OneAttemptNEQ applies the NEQ predicate on the "one_attempt" field.
func OneAttemptNEQ(v bool) predicate.Quiz {
	return predicate.Quiz(sql.FieldNEQ(FieldOneAttempt, v))
}

// ShowAnswersEQ applies the EQ predicate on the "show_answers" field.
func ShowAnswersEQ(v bool) predicate.Quiz {
	return predicate.Quiz(sql.FieldEQ(FieldShowAnswers, v))
}

// ShowAnswersNEQ applies the NEQ predicate on the "show_answers" field.
func ShowAnswersNEQ(v bool) predicate.Quiz {
	return predicate.Quiz(sql.FieldNEQ(FieldShowAnswers, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Quiz {
	return predicate.Quiz(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Quiz {
	return predicate.Quiz(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Quiz {
	return predicate.Quiz(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Quiz {
	return predicate.Quiz(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Quiz {
	return predicate.Quiz(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Quiz {
	return predicate.Quiz(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Quiz {
	return predicate.Quiz(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Quiz {
	return predicate.Quiz(sql.FieldLTE(FieldCreatedAt, v))
}

// CreatedAtIsNil applies the IsNil predicate on the "created_at" field.
func CreatedAtIsNil() predicate.Quiz {
	return predicate.Quiz(sql.FieldIsNull(FieldCreatedAt))
}

// CreatedAtNotNil applies the NotNil predicate on the "created_at" field.
func CreatedAtNotNil() predicate.Quiz {
	return predicate.Quiz(sql.FieldNotNull(FieldCreatedAt))
}

// HasCreatedBy applies the HasEdge predicate on the "created_by" edge.
func HasCreatedBy() predicate.Quiz {
	return predicate.Quiz(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, CreatedByTable, CreatedByColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCreatedByWith applies the HasEdge predicate on the "created_by" edge with a given conditions (other predicates).
func HasCreatedByWith(preds ...predicate.User) predicate.Quiz {
	return predicate.Quiz(func(s *sql.Selector) {
		step := newCreatedByStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasQuestions applies the HasEdge predicate on the "questions" edge.
func HasQuestions() predicate.Quiz {
	return predicate.Quiz(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, QuestionsTable, QuestionsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasQuestionsWith applies the HasEdge predicate on the "questions" edge with a given conditions (other predicates).
func HasQuestionsWith(preds ...predicate.Question) predicate.Quiz {
	return predicate.Quiz(func(s *sql.Selector) {
		step := newQuestionsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAttempts applies the HasEdge predicate on the "attempts" edge.
func HasAttempts() predicate.Quiz {
	return predicate.Quiz(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, AttemptsTable, AttemptsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAttemptsWith applies the HasEdge predicate on the "attempts" edge with a given conditions (other predicates).
func HasAttemptsWith(preds ...predicate.Attempt) predicate.Quiz {
	return predicate.Quiz(func(s *sql.Selector) {
		step := newAttemptsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Quiz) predicate.Quiz {
	return predicate.Quiz(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Quiz) predicate.Quiz {
	return predicate.Quiz(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Quiz) predicate.Quiz {
	return predicate.Quiz(sql.NotPredicates(p))
}
