// Code generated by ent, DO NOT EDIT.

package answer

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the answer type in the database.
	Label = "answer"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldText holds the string denoting the text field in the database.
	FieldText = "text"
	// FieldIsCorrect holds the string denoting the is_correct field in the database.
	FieldIsCorrect = "is_correct"
	// FieldOrderIndex holds the string denoting the order_index field in the database.
	FieldOrderIndex = "order_index"
	// EdgeQuestion holds the string denoting the question edge name in mutations.
	EdgeQuestion = "question"
	// EdgeAttemptAnswers holds the string denoting the attempt_answers edge name in mutations.
	EdgeAttemptAnswers = "attempt_answers"
	// Table holds the table name of the answer in the database.
	Table = "answers"
	// QuestionTable is the table that holds the question relation/edge.
	QuestionTable = "answers"
	// QuestionInverseTable is the table name for the Question entity.
	// It exists in this package in order to avoid circular dependency with the "question" package.
	QuestionInverseTable = "questions"
	// QuestionColumn is the table column denoting the question relation/edge.
	QuestionColumn = "question_answers"
	// AttemptAnswersTable is the table that holds the attempt_answers relation/edge.
	AttemptAnswersTable = "attempt_answers"
	// AttemptAnswersInverseTable is the table name for the AttemptAnswer entity.
	// It exists in this package in order to avoid circular dependency with the "attemptanswer" package.
	AttemptAnswersInverseTable = "attempt_answers"
	// AttemptAnswersColumn is the table column denoting the attempt_answers relation/edge.
	AttemptAnswersColumn = "answer_attempt_answers"
)

// Columns holds all SQL columns for answer fields.
var Columns = []string{
	FieldID,
	FieldText,
	FieldIsCorrect,
	FieldOrderIndex,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "answers"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"question_answers",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultIsCorrect holds the default value on creation for the "is_correct" field.
	DefaultIsCorrect bool
	// DefaultOrderIndex holds the default value on creation for the "order_index" field.
	DefaultOrderIndex int
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the Answer queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByText orders the results by the text field.
func ByText(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldText, opts...).ToFunc()
}

// ByIsCorrect orders the results by the is_correct field.
func ByIsCorrect(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsCorrect, opts...).ToFunc()
}

// ByOrderIndex orders the results by the order_index field.
func ByOrderIndex(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOrderIndex, opts...).ToFunc()
}

// ByQuestionField orders the results by question field.
func ByQuestionField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newQuestionStep(), sql.OrderByField(field, opts...))
	}
}

// ByAttemptAnswersCount orders the results by attempt_answers count.
func ByAttemptAnswersCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newAttemptAnswersStep(), opts...)
	}
}

// ByAttemptAnswers orders the results by attempt_answers terms.
func ByAttemptAnswers(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAttemptAnswersStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newQuestionStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(QuestionInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, QuestionTable, QuestionColumn),
	)
}
func newAttemptAnswersStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AttemptAnswersInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, AttemptAnswersTable, AttemptAnswersColumn),
	)
}
