// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"encore.app/ent/answer"
	"encore.app/ent/attemptanswer"
	"encore.app/ent/question"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// AnswerCreate is the builder for creating a Answer entity.
type AnswerCreate struct {
	config
	mutation *AnswerMutation
	hooks    []Hook
}

// SetText sets the "text" field.
func (_c *AnswerCreate) SetText(v string) *AnswerCreate {
	_c.mutation.SetText(v)
	return _c
}

// SetIsCorrect sets the "is_correct" field.
func (_c *AnswerCreate) SetIsCorrect(v bool) *AnswerCreate {
	_c.mutation.SetIsCorrect(v)
	return _c
}

// SetNillableIsCorrect sets the "is_correct" field if the given value is not nil.
func (_c *AnswerCreate) SetNillableIsCorrect(v *bool) *AnswerCreate {
	if v != nil {
		_c.SetIsCorrect(*v)
	}
	return _c
}

// SetOrderIndex sets the "order_index" field.
func (_c *AnswerCreate) SetOrderIndex(v int) *AnswerCreate {
	_c.mutation.SetOrderIndex(v)
	return _c
}

// SetNillableOrderIndex sets the "order_index" field if the given value is not nil.
func (_c *AnswerCreate) SetNillableOrderIndex(v *int) *AnswerCreate {
	if v != nil {
		_c.SetOrderIndex(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *AnswerCreate) SetID(v uuid.UUID) *AnswerCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *AnswerCreate) SetNillableID(v *uuid.UUID) *AnswerCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetQuestionID sets the "question" edge to the Question entity by ID.
func (_c *AnswerCreate) SetQuestionID(id uuid.UUID) *AnswerCreate {
	_c.mutation.SetQuestionID(id)
	return _c
}

// SetNillableQuestionID sets the "question" edge to the Question entity by ID if the given value is not nil.
func (_c *AnswerCreate) SetNillableQuestionID(id *uuid.UUID) *AnswerCreate {
	if id != nil {
		_c = _c.SetQuestionID(*id)
	}
	return _c
}

// SetQuestion sets the "question" edge to the Question entity.
func (_c *AnswerCreate) SetQuestion(v *Question) *AnswerCreate {
	return _c.SetQuestionID(v.ID)
}

// AddAttemptAnswerIDs adds the "attempt_answers" edge to the AttemptAnswer entity by IDs.
func (_c *AnswerCreate) AddAttemptAnswerIDs(ids ...uuid.UUID) *AnswerCreate {
	_c.mutation.AddAttemptAnswerIDs(ids...)
	return _c
}

// AddAttemptAnswers adds the "attempt_answers" edges to the AttemptAnswer entity.
func (_c *AnswerCreate) AddAttemptAnswers(v ...*AttemptAnswer) *AnswerCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddAttemptAnswerIDs(ids...)
}

// Mutation returns the AnswerMutation object of the builder.
func (_c *AnswerCreate) Mutation() *AnswerMutation {
	return _c.mutation
}

// Save creates the Answer in the database.
func (_c *AnswerCreate) Save(ctx context.Context) (*Answer, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AnswerCreate) SaveX(ctx context.Context) *Answer {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AnswerCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AnswerCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AnswerCreate) defaults() {
	if _, ok := _c.mutation.IsCorrect(); !ok {
		v := answer.DefaultIsCorrect
		_c.mutation.SetIsCorrect(v)
	}
	if _, ok := _c.mutation.OrderIndex(); !ok {
		v := answer.DefaultOrderIndex
		_c.mutation.SetOrderIndex(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := answer.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AnswerCreate) check() error {
	if _, ok := _c.mutation.Text(); !ok {
		return &ValidationError{Name: "text", err: errors.New(`ent: missing required field "Answer.text"`)}
	}
	if _, ok := _c.mutation.IsCorrect(); !ok {
		return &ValidationError{Name: "is_correct", err: errors.New(`ent: missing required field "Answer.is_correct"`)}
	}
	if _, ok := _c.mutation.OrderIndex(); !ok {
		return &ValidationError{Name: "order_index", err: errors.New(`ent: missing required field "Answer.order_index"`)}
	}
	return nil
}

func (_c *AnswerCreate) sqlSave(ctx context.Context) (*Answer, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AnswerCreate) createSpec() (*Answer, *sqlgraph.CreateSpec) {
	var (
		_node = &Answer{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(answer.Table, sqlgraph.NewFieldSpec(answer.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Text(); ok {
		_spec.SetField(answer.FieldText, field.TypeString, value)
		_node.Text = value
	}
	if value, ok := _c.mutation.IsCorrect(); ok {
		_spec.SetField(answer.FieldIsCorrect, field.TypeBool, value)
		_node.IsCorrect = value
	}
	if value, ok := _c.mutation.OrderIndex(); ok {
		_spec.SetField(answer.FieldOrderIndex, field.TypeInt, value)
		_node.OrderIndex = value
	}
	if nodes := _c.mutation.QuestionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   answer.QuestionTable,
			Columns: []string{answer.QuestionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(question.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.question_answers = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.AttemptAnswersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   answer.AttemptAnswersTable,
			Columns: []string{answer.AttemptAnswersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(attemptanswer.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// AnswerCreateBulk is the builder for creating many Answer entities in bulk.
type AnswerCreateBulk struct {
	config
	err      error
	builders []*AnswerCreate
}

// Save creates the Answer entities in the database.
func (_c *AnswerCreateBulk) Save(ctx context.Context) ([]*Answer, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Answer, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AnswerMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AnswerCreateBulk) SaveX(ctx context.Context) []*Answer {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AnswerCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AnswerCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
