// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"encore.app/ent/answer"
	"encore.app/ent/question"
	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// Answer is the model entity for the Answer schema.
type Answer struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Text holds the value of the "text" field.
	Text string `json:"text,omitempty"`
	// IsCorrect holds the value of the "is_correct" field.
	IsCorrect bool `json:"is_correct,omitempty"`
	// OrderIndex holds the value of the "order_index" field.
	OrderIndex int `json:"order_index,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the AnswerQuery when eager-loading is set.
	Edges            AnswerEdges `json:"edges"`
	question_answers *uuid.UUID
	selectValues     sql.SelectValues
}

// AnswerEdges holds the relations/edges for other nodes in the graph.
type AnswerEdges struct {
	// Question holds the value of the question edge.
	Question *Question `json:"question,omitempty"`
	// AttemptAnswers holds the value of the attempt_answers edge.
	AttemptAnswers []*AttemptAnswer `json:"attempt_answers,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// QuestionOrErr returns the Question value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AnswerEdges) QuestionOrErr() (*Question, error) {
	if e.Question != nil {
		return e.Question, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: question.Label}
	}
	return nil, &NotLoadedError{edge: "question"}
}

// AttemptAnswersOrErr returns the AttemptAnswers value or an error if the edge
// was not loaded in eager-loading.
func (e AnswerEdges) AttemptAnswersOrErr() ([]*AttemptAnswer, error) {
	if e.loadedTypes[1] {
		return e.AttemptAnswers, nil
	}
	return nil, &NotLoadedError{edge: "attempt_answers"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Answer) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case answer.FieldIsCorrect:
			values[i] = new(sql.NullBool)
		case answer.FieldOrderIndex:
			values[i] = new(sql.NullInt64)
		case answer.FieldText:
			values[i] = new(sql.NullString)
		case answer.FieldID:
			values[i] = new(uuid.UUID)
		case answer.ForeignKeys[0]: // question_answers
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Answer fields.
func (_m *Answer) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case answer.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case answer.FieldText:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field text", values[i])
			} else if value.Valid {
				_m.Text = value.String
			}
		case answer.FieldIsCorrect:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_correct", values[i])
			} else if value.Valid {
				_m.IsCorrect = value.Bool
			}
		case answer.FieldOrderIndex:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field order_index", values[i])
			} else if value.Valid {
				_m.OrderIndex = int(value.Int64)
			}
		case answer.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field question_answers", values[i])
			} else if value.Valid {
				_m.question_answers = new(uuid.UUID)
				*_m.question_answers = *value.S.(*uuid.UUID)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Answer.
// This includes values selected through modifiers, order, etc.
func (_m *Answer) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryQuestion queries the "question" edge of the Answer entity.
func (_m *Answer) QueryQuestion() *QuestionQuery {
	return NewAnswerClient(_m.config).QueryQuestion(_m)
}

// QueryAttemptAnswers queries the "attempt_answers" edge of the Answer entity.
func (_m *Answer) QueryAttemptAnswers() *AttemptAnswerQuery {
	return NewAnswerClient(_m.config).QueryAttemptAnswers(_m)
}

// Update returns a builder for updating this Answer.
// Note that you need to call Answer.Unwrap() before calling this method if this Answer
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Answer) Update() *AnswerUpdateOne {
	return NewAnswerClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Answer entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Answer) Unwrap() *Answer {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Answer is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Answer) String() string {
	var builder strings.Builder
	builder.WriteString("Answer(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("text=")
	builder.WriteString(_m.Text)
	builder.WriteString(", ")
	builder.WriteString("is_correct=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsCorrect))
	builder.WriteString(", ")
	builder.WriteString("order_index=")
	builder.WriteString(fmt.Sprintf("%v", _m.OrderIndex))
	builder.WriteByte(')')
	return builder.String()
}

// Answers is a parsable slice of Answer.
type Answers []*Answer
