// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"encore.app/ent/answer"
	"encore.app/ent/attemptanswer"
	"encore.app/ent/predicate"
	"encore.app/ent/question"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// AnswerUpdate is the builder for updating Answer entities.
type AnswerUpdate struct {
	config
	hooks    []Hook
	mutation *AnswerMutation
}

// Where appends a list predicates to the AnswerUpdate builder.
func (_u *AnswerUpdate) Where(ps ...predicate.Answer) *AnswerUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetText sets the "text" field.
func (_u *AnswerUpdate) SetText(v string) *AnswerUpdate {
	_u.mutation.SetText(v)
	return _u
}

// SetNillableText sets the "text" field if the given value is not nil.
func (_u *AnswerUpdate) SetNillableText(v *string) *AnswerUpdate {
	if v != nil {
		_u.SetText(*v)
	}
	return _u
}

// SetIsCorrect sets the "is_correct" field.
func (_u *AnswerUpdate) SetIsCorrect(v bool) *AnswerUpdate {
	_u.mutation.SetIsCorrect(v)
	return _u
}

// SetNillableIsCorrect sets the "is_correct" field if the given value is not nil.
func (_u *AnswerUpdate) SetNillableIsCorrect(v *bool) *AnswerUpdate {
	if v != nil {
		_u.SetIsCorrect(*v)
	}
	return _u
}

// SetOrderIndex sets the "order_index" field.
func (_u *AnswerUpdate) SetOrderIndex(v int) *AnswerUpdate {
	_u.mutation.ResetOrderIndex()
	_u.mutation.SetOrderIndex(v)
	return _u
}

// SetNillableOrderIndex sets the "order_index" field if the given value is not nil.
func (_u *AnswerUpdate) SetNillableOrderIndex(v *int) *AnswerUpdate {
	if v != nil {
		_u.SetOrderIndex(*v)
	}
	return _u
}

// AddOrderIndex adds value to the "order_index" field.
func (_u *AnswerUpdate) AddOrderIndex(v int) *AnswerUpdate {
	_u.mutation.AddOrderIndex(v)
	return _u
}

// SetQuestionID sets the "question" edge to the Question entity by ID.
func (_u *AnswerUpdate) SetQuestionID(id uuid.UUID) *AnswerUpdate {
	_u.mutation.SetQuestionID(id)
	return _u
}

// SetNillableQuestionID sets the "question" edge to the Question entity by ID if the given value is not nil.
func (_u *AnswerUpdate) SetNillableQuestionID(id *uuid.UUID) *AnswerUpdate {
	if id != nil {
		_u = _u.SetQuestionID(*id)
	}
	return _u
}

// SetQuestion sets the "question" edge to the Question entity.
func (_u *AnswerUpdate) SetQuestion(v *Question) *AnswerUpdate {
	return _u.SetQuestionID(v.ID)
}

// AddAttemptAnswerIDs adds the "attempt_answers" edge to the AttemptAnswer entity by IDs.
func (_u *AnswerUpdate) AddAttemptAnswerIDs(ids ...uuid.UUID) *AnswerUpdate {
	_u.mutation.AddAttemptAnswerIDs(ids...)
	return _u
}

// AddAttemptAnswers adds the "attempt_answers" edges to the AttemptAnswer entity.
func (_u *AnswerUpdate) AddAttemptAnswers(v ...*AttemptAnswer) *AnswerUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAttemptAnswerIDs(ids...)
}

// Mutation returns the AnswerMutation object of the builder.
func (_u *AnswerUpdate) Mutation() *AnswerMutation {
	return _u.mutation
}

// ClearQuestion clears the "question" edge to the Question entity.
func (_u *AnswerUpdate) ClearQuestion() *AnswerUpdate {
	_u.mutation.ClearQuestion()
	return _u
}

// ClearAttemptAnswers clears all "attempt_answers" edges to the AttemptAnswer entity.
func (_u *AnswerUpdate) ClearAttemptAnswers() *AnswerUpdate {
	_u.mutation.ClearAttemptAnswers()
	return _u
}

// RemoveAttemptAnswerIDs removes the "attempt_answers" edge to AttemptAnswer entities by IDs.
func (_u *AnswerUpdate) RemoveAttemptAnswerIDs(ids ...uuid.UUID) *AnswerUpdate {
	_u.mutation.RemoveAttemptAnswerIDs(ids...)
	return _u
}

// RemoveAttemptAnswers removes "attempt_answers" edges to AttemptAnswer entities.
func (_u *AnswerUpdate) RemoveAttemptAnswers(v ...*AttemptAnswer) *AnswerUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAttemptAnswerIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AnswerUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AnswerUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AnswerUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AnswerUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *AnswerUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(answer.Table, answer.Columns, sqlgraph.NewFieldSpec(answer.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Text(); ok {
		_spec.SetField(answer.FieldText, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsCorrect(); ok {
		_spec.SetField(answer.FieldIsCorrect, field.TypeBool, value)
	}
	if value, ok := _u.mutation.OrderIndex(); ok {
		_spec.SetField(answer.FieldOrderIndex, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedOrderIndex(); ok {
		_spec.AddField(answer.FieldOrderIndex, field.TypeInt, value)
	}
	if _u.mutation.QuestionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   answer.QuestionTable,
			Columns: []string{answer.QuestionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(question.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.QuestionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   answer.QuestionTable,
			Columns: []string{answer.QuestionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(question.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AttemptAnswersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   answer.AttemptAnswersTable,
			Columns: []string{answer.AttemptAnswersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(attemptanswer.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAttemptAnswersIDs(); len(nodes) > 0 && !_u.mutation.AttemptAnswersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   answer.AttemptAnswersTable,
			Columns: []string{answer.AttemptAnswersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(attemptanswer.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AttemptAnswersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   answer.AttemptAnswersTable,
			Columns: []string{answer.AttemptAnswersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(attemptanswer.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{answer.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AnswerUpdateOne is the builder for updating a single Answer entity.
type AnswerUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AnswerMutation
}

// SetText sets the "text" field.
func (_u *AnswerUpdateOne) SetText(v string) *AnswerUpdateOne {
	_u.mutation.SetText(v)
	return _u
}

// SetNillableText sets the "text" field if the given value is not nil.
func (_u *AnswerUpdateOne) SetNillableText(v *string) *AnswerUpdateOne {
	if v != nil {
		_u.SetText(*v)
	}
	return _u
}

// SetIsCorrect sets the "is_correct" field.
func (_u *AnswerUpdateOne) SetIsCorrect(v bool) *AnswerUpdateOne {
	_u.mutation.SetIsCorrect(v)
	return _u
}

// SetNillableIsCorrect sets the "is_correct" field if the given value is not nil.
func (_u *AnswerUpdateOne) SetNillableIsCorrect(v *bool) *AnswerUpdateOne {
	if v != nil {
		_u.SetIsCorrect(*v)
	}
	return _u
}

// SetOrderIndex sets the "order_index" field.
func (_u *AnswerUpdateOne) SetOrderIndex(v int) *AnswerUpdateOne {
	_u.mutation.ResetOrderIndex()
	_u.mutation.SetOrderIndex(v)
	return _u
}

// SetNillableOrderIndex sets the "order_index" field if the given value is not nil.
func (_u *AnswerUpdateOne) SetNillableOrderIndex(v *int) *AnswerUpdateOne {
	if v != nil {
		_u.SetOrderIndex(*v)
	}
	return _u
}

// AddOrderIndex adds value to the "order_index" field.
func (_u *AnswerUpdateOne) AddOrderIndex(v int) *AnswerUpdateOne {
	_u.mutation.AddOrderIndex(v)
	return _u
}

// SetQuestionID sets the "question" edge to the Question entity by ID.
func (_u *AnswerUpdateOne) SetQuestionID(id uuid.UUID) *AnswerUpdateOne {
	_u.mutation.SetQuestionID(id)
	return _u
}

// SetNillableQuestionID sets the "question" edge to the Question entity by ID if the given value is not nil.
func (_u *AnswerUpdateOne) SetNillableQuestionID(id *uuid.UUID) *AnswerUpdateOne {
	if id != nil {
		_u = _u.SetQuestionID(*id)
	}
	return _u
}

// SetQuestion sets the "question" edge to the Question entity.
func (_u *AnswerUpdateOne) SetQuestion(v *Question) *AnswerUpdateOne {
	return _u.SetQuestionID(v.ID)
}

// AddAttemptAnswerIDs adds the "attempt_answers" edge to the AttemptAnswer entity by IDs.
func (_u *AnswerUpdateOne) AddAttemptAnswerIDs(ids ...uuid.UUID) *AnswerUpdateOne {
	_u.mutation.AddAttemptAnswerIDs(ids...)
	return _u
}

// AddAttemptAnswers adds the "attempt_answers" edges to the AttemptAnswer entity.
func (_u *AnswerUpdateOne) AddAttemptAnswers(v ...*AttemptAnswer) *AnswerUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAttemptAnswerIDs(ids...)
}

// Mutation returns the AnswerMutation object of the builder.
func (_u *AnswerUpdateOne) Mutation() *AnswerMutation {
	return _u.mutation
}

// ClearQuestion clears the "question" edge to the Question entity.
func (_u *AnswerUpdateOne) ClearQuestion() *AnswerUpdateOne {
	_u.mutation.ClearQuestion()
	return _u
}

// ClearAttemptAnswers clears all "attempt_answers" edges to the AttemptAnswer entity.
func (_u *AnswerUpdateOne) ClearAttemptAnswers() *AnswerUpdateOne {
	_u.mutation.ClearAttemptAnswers()
	return _u
}

// RemoveAttemptAnswerIDs removes the "attempt_answers" edge to AttemptAnswer entities by IDs.
func (_u *AnswerUpdateOne) RemoveAttemptAnswerIDs(ids ...uuid.UUID) *AnswerUpdateOne {
	_u.mutation.RemoveAttemptAnswerIDs(ids...)
	return _u
}

// RemoveAttemptAnswers removes "attempt_answers" edges to AttemptAnswer entities.
func (_u *AnswerUpdateOne) RemoveAttemptAnswers(v ...*AttemptAnswer) *AnswerUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAttemptAnswerIDs(ids...)
}

// Where appends a list predicates to the AnswerUpdate builder.
func (_u *AnswerUpdateOne) Where(ps ...predicate.Answer) *AnswerUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AnswerUpdateOne) Select(field string, fields ...string) *AnswerUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Answer entity.
func (_u *AnswerUpdateOne) Save(ctx context.Context) (*Answer, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AnswerUpdateOne) SaveX(ctx context.Context) *Answer {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AnswerUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AnswerUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *AnswerUpdateOne) sqlSave(ctx context.Context) (_node *Answer, err error) {
	_spec := sqlgraph.NewUpdateSpec(answer.Table, answer.Columns, sqlgraph.NewFieldSpec(answer.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Answer.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, answer.FieldID)
		for _, f := range fields {
			if !answer.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != answer.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Text(); ok {
		_spec.SetField(answer.FieldText, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsCorrect(); ok {
		_spec.SetField(answer.FieldIsCorrect, field.TypeBool, value)
	}
	if value, ok := _u.mutation.OrderIndex(); ok {
		_spec.SetField(answer.FieldOrderIndex, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedOrderIndex(); ok {
		_spec.AddField(answer.FieldOrderIndex, field.TypeInt, value)
	}
	if _u.mutation.QuestionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   answer.QuestionTable,
			Columns: []string{answer.QuestionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(question.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.QuestionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   answer.QuestionTable,
			Columns: []string{answer.QuestionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(question.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AttemptAnswersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   answer.AttemptAnswersTable,
			Columns: []string{answer.AttemptAnswersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(attemptanswer.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAttemptAnswersIDs(); len(nodes) > 0 && !_u.mutation.AttemptAnswersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   answer.AttemptAnswersTable,
			Columns: []string{answer.AttemptAnswersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(attemptanswer.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AttemptAnswersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   answer.AttemptAnswersTable,
			Columns: []string{answer.AttemptAnswersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(attemptanswer.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Answer{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{answer.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
