// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"encore.app/ent/attempt"
	"encore.app/ent/attemptanswer"
	"encore.app/ent/quiz"
	"encore.app/ent/user"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// AttemptCreate is the builder for creating a Attempt entity.
type AttemptCreate struct {
	config
	mutation *AttemptMutation
	hooks    []Hook
}

// SetScore sets the "score" field.
func (_c *AttemptCreate) SetScore(v int) *AttemptCreate {
	_c.mutation.SetScore(v)
	return _c
}

// SetTotal sets the "total" field.
func (_c *AttemptCreate) SetTotal(v int) *AttemptCreate {
	_c.mutation.SetTotal(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *AttemptCreate) SetCreatedAt(v time.Time) *AttemptCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AttemptCreate) SetNillableCreatedAt(v *time.Time) *AttemptCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *AttemptCreate) SetID(v uuid.UUID) *AttemptCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *AttemptCreate) SetNillableID(v *uuid.UUID) *AttemptCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetQuizID sets the "quiz" edge to the Quiz entity by ID.
func (_c *AttemptCreate) SetQuizID(id uuid.UUID) *AttemptCreate {
	_c.mutation.SetQuizID(id)
	return _c
}

// SetNillableQuizID sets the "quiz" edge to the Quiz entity by ID if the given value is not nil.
func (_c *AttemptCreate) SetNillableQuizID(id *uuid.UUID) *AttemptCreate {
	if id != nil {
		_c = _c.SetQuizID(*id)
	}
	return _c
}

// SetQuiz sets the "quiz" edge to the Quiz entity.
func (_c *AttemptCreate) SetQuiz(v *Quiz) *AttemptCreate {
	return _c.SetQuizID(v.ID)
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_c *AttemptCreate) SetUserID(id uuid.UUID) *AttemptCreate {
	_c.mutation.SetUserID(id)
	return _c
}

// SetNillableUserID sets the "user" edge to the User entity by ID if the given value is not nil.
func (_c *AttemptCreate) SetNillableUserID(id *uuid.UUID) *AttemptCreate {
	if id != nil {
		_c = _c.SetUserID(*id)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *AttemptCreate) SetUser(v *User) *AttemptCreate {
	return _c.SetUserID(v.ID)
}

// AddAttemptAnswerIDs adds the "attempt_answers" edge to the AttemptAnswer entity by IDs.
func (_c *AttemptCreate) AddAttemptAnswerIDs(ids ...uuid.UUID) *AttemptCreate {
	_c.mutation.AddAttemptAnswerIDs(ids...)
	return _c
}

// AddAttemptAnswers adds the "attempt_answers" edges to the AttemptAnswer entity.
func (_c *AttemptCreate) AddAttemptAnswers(v ...*AttemptAnswer) *AttemptCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddAttemptAnswerIDs(ids...)
}

// Mutation returns the AttemptMutation object of the builder.
func (_c *AttemptCreate) Mutation() *AttemptMutation {
	return _c.mutation
}

// Save creates the Attempt in the database.
func (_c *AttemptCreate) Save(ctx context.Context) (*Attempt, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AttemptCreate) SaveX(ctx context.Context) *Attempt {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AttemptCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AttemptCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AttemptCreate) defaults() {
	if _, ok := _c.mutation.ID(); !ok {
		v := attempt.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AttemptCreate) check() error {
	if _, ok := _c.mutation.Score(); !ok {
		return &ValidationError{Name: "score", err: errors.New(`ent: missing required field "Attempt.score"`)}
	}
	if _, ok := _c.mutation.Total(); !ok {
		return &ValidationError{Name: "total", err: errors.New(`ent: missing required field "Attempt.total"`)}
	}
	return nil
}

func (_c *AttemptCreate) sqlSave(ctx context.Context) (*Attempt, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AttemptCreate) createSpec() (*Attempt, *sqlgraph.CreateSpec) {
	var (
		_node = &Attempt{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(attempt.Table, sqlgraph.NewFieldSpec(attempt.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Score(); ok {
		_spec.SetField(attempt.FieldScore, field.TypeInt, value)
		_node.Score = value
	}
	if value, ok := _c.mutation.Total(); ok {
		_spec.SetField(attempt.FieldTotal, field.TypeInt, value)
		_node.Total = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(attempt.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.QuizIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   attempt.QuizTable,
			Columns: []string{attempt.QuizColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(quiz.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.quiz_attempts = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   attempt.UserTable,
			Columns: []string{attempt.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_attempts = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.AttemptAnswersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   attempt.AttemptAnswersTable,
			Columns: []string{attempt.AttemptAnswersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(attemptanswer.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// AttemptCreateBulk is the builder for creating many Attempt entities in bulk.
type AttemptCreateBulk struct {
	config
	err      error
	builders []*AttemptCreate
}

// Save creates the Attempt entities in the database.
func (_c *AttemptCreateBulk) Save(ctx context.Context) ([]*Attempt, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Attempt, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AttemptMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AttemptCreateBulk) SaveX(ctx context.Context) []*Attempt {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AttemptCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AttemptCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
