// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"encore.app/ent/attempt"
	"encore.app/ent/attemptanswer"
	"encore.app/ent/predicate"
	"encore.app/ent/quiz"
	"encore.app/ent/user"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// AttemptUpdate is the builder for updating Attempt entities.
type AttemptUpdate struct {
	config
	hooks    []Hook
	mutation *AttemptMutation
}

// Where appends a list predicates to the AttemptUpdate builder.
func (_u *AttemptUpdate) Where(ps ...predicate.Attempt) *AttemptUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetScore sets the "score" field.
func (_u *AttemptUpdate) SetScore(v int) *AttemptUpdate {
	_u.mutation.ResetScore()
	_u.mutation.SetScore(v)
	return _u
}

// SetNillableScore sets the "score" field if the given value is not nil.
func (_u *AttemptUpdate) SetNillableScore(v *int) *AttemptUpdate {
	if v != nil {
		_u.SetScore(*v)
	}
	return _u
}

// AddScore adds value to the "score" field.
func (_u *AttemptUpdate) AddScore(v int) *AttemptUpdate {
	_u.mutation.AddScore(v)
	return _u
}

// SetTotal sets the "total" field.
func (_u *AttemptUpdate) SetTotal(v int) *AttemptUpdate {
	_u.mutation.ResetTotal()
	_u.mutation.SetTotal(v)
	return _u
}

// SetNillableTotal sets the "total" field if the given value is not nil.
func (_u *AttemptUpdate) SetNillableTotal(v *int) *AttemptUpdate {
	if v != nil {
		_u.SetTotal(*v)
	}
	return _u
}

// AddTotal adds value to the "total" field.
func (_u *AttemptUpdate) AddTotal(v int) *AttemptUpdate {
	_u.mutation.AddTotal(v)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *AttemptUpdate) SetCreatedAt(v time.Time) *AttemptUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *AttemptUpdate) SetNillableCreatedAt(v *time.Time) *AttemptUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// ClearCreatedAt clears the value of the "created_at" field.
func (_u *AttemptUpdate) ClearCreatedAt() *AttemptUpdate {
	_u.mutation.ClearCreatedAt()
	return _u
}

// SetQuizID sets the "quiz" edge to the Quiz entity by ID.
func (_u *AttemptUpdate) SetQuizID(id uuid.UUID) *AttemptUpdate {
	_u.mutation.SetQuizID(id)
	return _u
}

// SetNillableQuizID sets the "quiz" edge to the Quiz entity by ID if the given value is not nil.
func (_u *AttemptUpdate) SetNillableQuizID(id *uuid.UUID) *AttemptUpdate {
	if id != nil {
		_u = _u.SetQuizID(*id)
	}
	return _u
}

// SetQuiz sets the "quiz" edge to the Quiz entity.
func (_u *AttemptUpdate) SetQuiz(v *Quiz) *AttemptUpdate {
	return _u.SetQuizID(v.ID)
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_u *AttemptUpdate) SetUserID(id uuid.UUID) *AttemptUpdate {
	_u.mutation.SetUserID(id)
	return _u
}

// SetNillableUserID sets the "user" edge to the User entity by ID if the given value is not nil.
func (_u *AttemptUpdate) SetNillableUserID(id *uuid.UUID) *AttemptUpdate {
	if id != nil {
		_u = _u.SetUserID(*id)
	}
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *AttemptUpdate) SetUser(v *User) *AttemptUpdate {
	return _u.SetUserID(v.ID)
}

// AddAttemptAnswerIDs adds the "attempt_answers" edge to the AttemptAnswer entity by IDs.
func (_u *AttemptUpdate) AddAttemptAnswerIDs(ids ...uuid.UUID) *AttemptUpdate {
	_u.mutation.AddAttemptAnswerIDs(ids...)
	return _u
}

// AddAttemptAnswers adds the "attempt_answers" edges to the AttemptAnswer entity.
func (_u *AttemptUpdate) AddAttemptAnswers(v ...*AttemptAnswer) *AttemptUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAttemptAnswerIDs(ids...)
}

// Mutation returns the AttemptMutation object of the builder.
func (_u *AttemptUpdate) Mutation() *AttemptMutation {
	return _u.mutation
}

// ClearQuiz clears the "quiz" edge to the Quiz entity.
func (_u *AttemptUpdate) ClearQuiz() *AttemptUpdate {
	_u.mutation.ClearQuiz()
	return _u
}

// ClearUser clears the "user" edge to the User entity.
func (_u *AttemptUpdate) ClearUser() *AttemptUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearAttemptAnswers clears all "attempt_answers" edges to the AttemptAnswer entity.
func (_u *AttemptUpdate) ClearAttemptAnswers() *AttemptUpdate {
	_u.mutation.ClearAttemptAnswers()
	return _u
}

// RemoveAttemptAnswerIDs removes the "attempt_answers" edge to AttemptAnswer entities by IDs.
func (_u *AttemptUpdate) RemoveAttemptAnswerIDs(ids ...uuid.UUID) *AttemptUpdate {
	_u.mutation.RemoveAttemptAnswerIDs(ids...)
	return _u
}

// RemoveAttemptAnswers removes "attempt_answers" edges to AttemptAnswer entities.
func (_u *AttemptUpdate) RemoveAttemptAnswers(v ...*AttemptAnswer) *AttemptUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAttemptAnswerIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AttemptUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AttemptUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AttemptUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AttemptUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *AttemptUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(attempt.Table, attempt.Columns, sqlgraph.NewFieldSpec(attempt.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Score(); ok {
		_spec.SetField(attempt.FieldScore, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedScore(); ok {
		_spec.AddField(attempt.FieldScore, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Total(); ok {
		_spec.SetField(attempt.FieldTotal, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTotal(); ok {
		_spec.AddField(attempt.FieldTotal, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(attempt.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(attempt.FieldCreatedAt, field.TypeTime)
	}
	if _u.mutation.QuizCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   attempt.QuizTable,
			Columns: []string{attempt.QuizColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(quiz.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.QuizIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   attempt.QuizTable,
			Columns: []string{attempt.QuizColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(quiz.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   attempt.UserTable,
			Columns: []string{attempt.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   attempt.UserTable,
			Columns: []string{attempt.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AttemptAnswersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   attempt.AttemptAnswersTable,
			Columns: []string{attempt.AttemptAnswersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(attemptanswer.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAttemptAnswersIDs(); len(nodes) > 0 && !_u.mutation.AttemptAnswersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   attempt.AttemptAnswersTable,
			Columns: []string{attempt.AttemptAnswersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(attemptanswer.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AttemptAnswersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   attempt.AttemptAnswersTable,
			Columns: []string{attempt.AttemptAnswersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(attemptanswer.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{attempt.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AttemptUpdateOne is the builder for updating a single Attempt entity.
type AttemptUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AttemptMutation
}

// SetScore sets the "score" field.
func (_u *AttemptUpdateOne) SetScore(v int) *AttemptUpdateOne {
	_u.mutation.ResetScore()
	_u.mutation.SetScore(v)
	return _u
}

// SetNillableScore sets the "score" field if the given value is not nil.
func (_u *AttemptUpdateOne) SetNillableScore(v *int) *AttemptUpdateOne {
	if v != nil {
		_u.SetScore(*v)
	}
	return _u
}

// AddScore adds value to the "score" field.
func (_u *AttemptUpdateOne) AddScore(v int) *AttemptUpdateOne {
	_u.mutation.AddScore(v)
	return _u
}

// SetTotal sets the "total" field.
func (_u *AttemptUpdateOne) SetTotal(v int) *AttemptUpdateOne {
	_u.mutation.ResetTotal()
	_u.mutation.SetTotal(v)
	return _u
}

// SetNillableTotal sets the "total" field if the given value is not nil.
func (_u *AttemptUpdateOne) SetNillableTotal(v *int) *AttemptUpdateOne {
	if v != nil {
		_u.SetTotal(*v)
	}
	return _u
}

// AddTotal adds value to the "total" field.
func (_u *AttemptUpdateOne) AddTotal(v int) *AttemptUpdateOne {
	_u.mutation.AddTotal(v)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *AttemptUpdateOne) SetCreatedAt(v time.Time) *AttemptUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *AttemptUpdateOne) SetNillableCreatedAt(v *time.Time) *AttemptUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// ClearCreatedAt clears the value of the "created_at" field.
func (_u *AttemptUpdateOne) ClearCreatedAt() *AttemptUpdateOne {
	_u.mutation.ClearCreatedAt()
	return _u
}

// SetQuizID sets the "quiz" edge to the Quiz entity by ID.
func (_u *AttemptUpdateOne) SetQuizID(id uuid.UUID) *AttemptUpdateOne {
	_u.mutation.SetQuizID(id)
	return _u
}

// SetNillableQuizID sets the "quiz" edge to the Quiz entity by ID if the given value is not nil.
func (_u *AttemptUpdateOne) SetNillableQuizID(id *uuid.UUID) *AttemptUpdateOne {
	if id != nil {
		_u = _u.SetQuizID(*id)
	}
	return _u
}

// SetQuiz sets the "quiz" edge to the Quiz entity.
func (_u *AttemptUpdateOne) SetQuiz(v *Quiz) *AttemptUpdateOne {
	return _u.SetQuizID(v.ID)
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_u *AttemptUpdateOne) SetUserID(id uuid.UUID) *AttemptUpdateOne {
	_u.mutation.SetUserID(id)
	return _u
}

// SetNillableUserID sets the "user" edge to the User entity by ID if the given value is not nil.
func (_u *AttemptUpdateOne) SetNillableUserID(id *uuid.UUID) *AttemptUpdateOne {
	if id != nil {
		_u = _u.SetUserID(*id)
	}
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *AttemptUpdateOne) SetUser(v *User) *AttemptUpdateOne {
	return _u.SetUserID(v.ID)
}

// AddAttemptAnswerIDs adds the "attempt_answers" edge to the AttemptAnswer entity by IDs.
func (_u *AttemptUpdateOne) AddAttemptAnswerIDs(ids ...uuid.UUID) *AttemptUpdateOne {
	_u.mutation.AddAttemptAnswerIDs(ids...)
	return _u
}

// AddAttemptAnswers adds the "attempt_answers" edges to the AttemptAnswer entity.
func (_u *AttemptUpdateOne) AddAttemptAnswers(v ...*AttemptAnswer) *AttemptUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAttemptAnswerIDs(ids...)
}

// Mutation returns the AttemptMutation object of the builder.
func (_u *AttemptUpdateOne) Mutation() *AttemptMutation {
	return _u.mutation
}

// ClearQuiz clears the "quiz" edge to the Quiz entity.
func (_u *AttemptUpdateOne) ClearQuiz() *AttemptUpdateOne {
	_u.mutation.ClearQuiz()
	return _u
}

// ClearUser clears the "user" edge to the User entity.
func (_u *AttemptUpdateOne) ClearUser() *AttemptUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearAttemptAnswers clears all "attempt_answers" edges to the AttemptAnswer entity.
func (_u *AttemptUpdateOne) ClearAttemptAnswers() *AttemptUpdateOne {
	_u.mutation.ClearAttemptAnswers()
	return _u
}

// RemoveAttemptAnswerIDs removes the "attempt_answers" edge to AttemptAnswer entities by IDs.
func (_u *AttemptUpdateOne) RemoveAttemptAnswerIDs(ids ...uuid.UUID) *AttemptUpdateOne {
	_u.mutation.RemoveAttemptAnswerIDs(ids...)
	return _u
}

// RemoveAttemptAnswers removes "attempt_answers" edges to AttemptAnswer entities.
func (_u *AttemptUpdateOne) RemoveAttemptAnswers(v ...*AttemptAnswer) *AttemptUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAttemptAnswerIDs(ids...)
}

// Where appends a list predicates to the AttemptUpdate builder.
func (_u *AttemptUpdateOne) Where(ps ...predicate.Attempt) *AttemptUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AttemptUpdateOne) Select(field string, fields ...string) *AttemptUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Attempt entity.
func (_u *AttemptUpdateOne) Save(ctx context.Context) (*Attempt, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AttemptUpdateOne) SaveX(ctx context.Context) *Attempt {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AttemptUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AttemptUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *AttemptUpdateOne) sqlSave(ctx context.Context) (_node *Attempt, err error) {
	_spec := sqlgraph.NewUpdateSpec(attempt.Table, attempt.Columns, sqlgraph.NewFieldSpec(attempt.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Attempt.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, attempt.FieldID)
		for _, f := range fields {
			if !attempt.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != attempt.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Score(); ok {
		_spec.SetField(attempt.FieldScore, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedScore(); ok {
		_spec.AddField(attempt.FieldScore, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Total(); ok {
		_spec.SetField(attempt.FieldTotal, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTotal(); ok {
		_spec.AddField(attempt.FieldTotal, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(attempt.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(attempt.FieldCreatedAt, field.TypeTime)
	}
	if _u.mutation.QuizCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   attempt.QuizTable,
			Columns: []string{attempt.QuizColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(quiz.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.QuizIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   attempt.QuizTable,
			Columns: []string{attempt.QuizColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(quiz.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   attempt.UserTable,
			Columns: []string{attempt.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   attempt.UserTable,
			Columns: []string{attempt.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AttemptAnswersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   attempt.AttemptAnswersTable,
			Columns: []string{attempt.AttemptAnswersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(attemptanswer.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAttemptAnswersIDs(); len(nodes) > 0 && !_u.mutation.AttemptAnswersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   attempt.AttemptAnswersTable,
			Columns: []string{attempt.AttemptAnswersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(attemptanswer.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AttemptAnswersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   attempt.AttemptAnswersTable,
			Columns: []string{attempt.AttemptAnswersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(attemptanswer.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Attempt{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{attempt.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
