// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"encore.app/ent/attempt"
	"encore.app/ent/attemptanswer"
	"encore.app/ent/predicate"
	"encore.app/ent/quiz"
	"encore.app/ent/user"
	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// AttemptQuery is the builder for querying Attempt entities.
type AttemptQuery struct {
	config
	ctx                *QueryContext
	order              []attempt.OrderOption
	inters             []Interceptor
	predicates         []predicate.Attempt
	withQuiz           *QuizQuery
	withUser           *UserQuery
	withAttemptAnswers *AttemptAnswerQuery
	withFKs            bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the AttemptQuery builder.
func (_q *AttemptQuery) Where(ps ...predicate.Attempt) *AttemptQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *AttemptQuery) Limit(limit int) *AttemptQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *AttemptQuery) Offset(offset int) *AttemptQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *AttemptQuery) Unique(unique bool) *AttemptQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *AttemptQuery) Order(o ...attempt.OrderOption) *AttemptQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryQuiz chains the current query on the "quiz" edge.
func (_q *AttemptQuery) QueryQuiz() *QuizQuery {
	query := (&QuizClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(attempt.Table, attempt.FieldID, selector),
			sqlgraph.To(quiz.Table, quiz.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, attempt.QuizTable, attempt.QuizColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryUser chains the current query on the "user" edge.
func (_q *AttemptQuery) QueryUser() *UserQuery {
	query := (&UserClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(attempt.Table, attempt.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, attempt.UserTable, attempt.UserColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryAttemptAnswers chains the current query on the "attempt_answers" edge.
func (_q *AttemptQuery) QueryAttemptAnswers() *AttemptAnswerQuery {
	query := (&AttemptAnswerClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(attempt.Table, attempt.FieldID, selector),
			sqlgraph.To(attemptanswer.Table, attemptanswer.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, attempt.AttemptAnswersTable, attempt.AttemptAnswersColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Attempt entity from the query.
// Returns a *NotFoundError when no Attempt was found.
func (_q *AttemptQuery) First(ctx context.Context) (*Attempt, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{attempt.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *AttemptQuery) FirstX(ctx context.Context) *Attempt {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Attempt ID from the query.
// Returns a *NotFoundError when no Attempt ID was found.
func (_q *AttemptQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{attempt.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *AttemptQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Attempt entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Attempt entity is found.
// Returns a *NotFoundError when no Attempt entities are found.
func (_q *AttemptQuery) Only(ctx context.Context) (*Attempt, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{attempt.Label}
	default:
		return nil, &NotSingularError{attempt.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *AttemptQuery) OnlyX(ctx context.Context) *Attempt {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Attempt ID in the query.
// Returns a *NotSingularError when more than one Attempt ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *AttemptQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{attempt.Label}
	default:
		err = &NotSingularError{attempt.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *AttemptQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Attempts.
func (_q *AttemptQuery) All(ctx context.Context) ([]*Attempt, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Attempt, *AttemptQuery]()
	return withInterceptors[[]*Attempt](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *AttemptQuery) AllX(ctx context.Context) []*Attempt {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Attempt IDs.
func (_q *AttemptQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(attempt.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *AttemptQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *AttemptQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*AttemptQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *AttemptQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *AttemptQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *AttemptQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the AttemptQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *AttemptQuery) Clone() *AttemptQuery {
	if _q == nil {
		return nil
	}
	return &AttemptQuery{
		config:             _q.config,
		ctx:                _q.ctx.Clone(),
		order:              append([]attempt.OrderOption{}, _q.order...),
		inters:             append([]Interceptor{}, _q.inters...),
		predicates:         append([]predicate.Attempt{}, _q.predicates...),
		withQuiz:           _q.withQuiz.Clone(),
		withUser:           _q.withUser.Clone(),
		withAttemptAnswers: _q.withAttemptAnswers.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithQuiz tells the query-builder to eager-load the nodes that are connected to
// the "quiz" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *AttemptQuery) WithQuiz(opts ...func(*QuizQuery)) *AttemptQuery {
	query := (&QuizClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withQuiz = query
	return _q
}

// WithUser tells the query-builder to eager-load the nodes that are connected to
// the "user" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *AttemptQuery) WithUser(opts ...func(*UserQuery)) *AttemptQuery {
	query := (&UserClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withUser = query
	return _q
}

// WithAttemptAnswers tells the query-builder to eager-load the nodes that are connected to
// the "attempt_answers" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *AttemptQuery) WithAttemptAnswers(opts ...func(*AttemptAnswerQuery)) *AttemptQuery {
	query := (&AttemptAnswerClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withAttemptAnswers = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Score int `json:"score,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Attempt.Query().
//		GroupBy(attempt.FieldScore).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *AttemptQuery) GroupBy(field string, fields ...string) *AttemptGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &AttemptGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = attempt.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Score int `json:"score,omitempty"`
//	}
//
//	client.Attempt.Query().
//		Select(attempt.FieldScore).
//		Scan(ctx, &v)
func (_q *AttemptQuery) Select(fields ...string) *AttemptSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &AttemptSelect{AttemptQuery: _q}
	sbuild.label = attempt.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a AttemptSelect configured with the given aggregations.
func (_q *AttemptQuery) Aggregate(fns ...AggregateFunc) *AttemptSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *AttemptQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !attempt.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *AttemptQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Attempt, error) {
	var (
		nodes       = []*Attempt{}
		withFKs     = _q.withFKs
		_spec       = _q.querySpec()
		loadedTypes = [3]bool{
			_q.withQuiz != nil,
			_q.withUser != nil,
			_q.withAttemptAnswers != nil,
		}
	)
	if _q.withQuiz != nil || _q.withUser != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, attempt.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Attempt).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Attempt{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withQuiz; query != nil {
		if err := _q.loadQuiz(ctx, query, nodes, nil,
			func(n *Attempt, e *Quiz) { n.Edges.Quiz = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withUser; query != nil {
		if err := _q.loadUser(ctx, query, nodes, nil,
			func(n *Attempt, e *User) { n.Edges.User = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withAttemptAnswers; query != nil {
		if err := _q.loadAttemptAnswers(ctx, query, nodes,
			func(n *Attempt) { n.Edges.AttemptAnswers = []*AttemptAnswer{} },
			func(n *Attempt, e *AttemptAnswer) { n.Edges.AttemptAnswers = append(n.Edges.AttemptAnswers, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *AttemptQuery) loadQuiz(ctx context.Context, query *QuizQuery, nodes []*Attempt, init func(*Attempt), assign func(*Attempt, *Quiz)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*Attempt)
	for i := range nodes {
		if nodes[i].quiz_attempts == nil {
			continue
		}
		fk := *nodes[i].quiz_attempts
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(quiz.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "quiz_attempts" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *AttemptQuery) loadUser(ctx context.Context, query *UserQuery, nodes []*Attempt, init func(*Attempt), assign func(*Attempt, *User)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*Attempt)
	for i := range nodes {
		if nodes[i].user_attempts == nil {
			continue
		}
		fk := *nodes[i].user_attempts
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "user_attempts" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *AttemptQuery) loadAttemptAnswers(ctx context.Context, query *AttemptAnswerQuery, nodes []*Attempt, init func(*Attempt), assign func(*Attempt, *AttemptAnswer)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*Attempt)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.AttemptAnswer(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(attempt.AttemptAnswersColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.attempt_attempt_answers
		if fk == nil {
			return fmt.Errorf(`foreign-key "attempt_attempt_answers" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "attempt_attempt_answers" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *AttemptQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *AttemptQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(attempt.Table, attempt.Columns, sqlgraph.NewFieldSpec(attempt.FieldID, field.TypeUUID))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, attempt.FieldID)
		for i := range fields {
			if fields[i] != attempt.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *AttemptQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(attempt.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = attempt.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// AttemptGroupBy is the group-by builder for Attempt entities.
type AttemptGroupBy struct {
	selector
	build *AttemptQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *AttemptGroupBy) Aggregate(fns ...AggregateFunc) *AttemptGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *AttemptGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*AttemptQuery, *AttemptGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *AttemptGroupBy) sqlScan(ctx context.Context, root *AttemptQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// AttemptSelect is the builder for selecting fields of Attempt entities.
type AttemptSelect struct {
	*AttemptQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *AttemptSelect) Aggregate(fns ...AggregateFunc) *AttemptSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *AttemptSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*AttemptQuery, *AttemptSelect](ctx, _s.AttemptQuery, _s, _s.inters, v)
}

func (_s *AttemptSelect) sqlScan(ctx context.Context, root *AttemptQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
