// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"encore.app/ent/attempt"
	"encore.app/ent/quiz"
	"encore.app/ent/user"
	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// Attempt is the model entity for the Attempt schema.
type Attempt struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Score holds the value of the "score" field.
	Score int `json:"score,omitempty"`
	// Total holds the value of the "total" field.
	Total int `json:"total,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the AttemptQuery when eager-loading is set.
	Edges         AttemptEdges `json:"edges"`
	quiz_attempts *uuid.UUID
	user_attempts *uuid.UUID
	selectValues  sql.SelectValues
}

// AttemptEdges holds the relations/edges for other nodes in the graph.
type AttemptEdges struct {
	// Quiz holds the value of the quiz edge.
	Quiz *Quiz `json:"quiz,omitempty"`
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// AttemptAnswers holds the value of the attempt_answers edge.
	AttemptAnswers []*AttemptAnswer `json:"attempt_answers,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// QuizOrErr returns the Quiz value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AttemptEdges) QuizOrErr() (*Quiz, error) {
	if e.Quiz != nil {
		return e.Quiz, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: quiz.Label}
	}
	return nil, &NotLoadedError{edge: "quiz"}
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AttemptEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// AttemptAnswersOrErr returns the AttemptAnswers value or an error if the edge
// was not loaded in eager-loading.
func (e AttemptEdges) AttemptAnswersOrErr() ([]*AttemptAnswer, error) {
	if e.loadedTypes[2] {
		return e.AttemptAnswers, nil
	}
	return nil, &NotLoadedError{edge: "attempt_answers"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Attempt) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case attempt.FieldScore, attempt.FieldTotal:
			values[i] = new(sql.NullInt64)
		case attempt.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case attempt.FieldID:
			values[i] = new(uuid.UUID)
		case attempt.ForeignKeys[0]: // quiz_attempts
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case attempt.ForeignKeys[1]: // user_attempts
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Attempt fields.
func (_m *Attempt) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case attempt.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case attempt.FieldScore:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field score", values[i])
			} else if value.Valid {
				_m.Score = int(value.Int64)
			}
		case attempt.FieldTotal:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field total", values[i])
			} else if value.Valid {
				_m.Total = int(value.Int64)
			}
		case attempt.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case attempt.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field quiz_attempts", values[i])
			} else if value.Valid {
				_m.quiz_attempts = new(uuid.UUID)
				*_m.quiz_attempts = *value.S.(*uuid.UUID)
			}
		case attempt.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field user_attempts", values[i])
			} else if value.Valid {
				_m.user_attempts = new(uuid.UUID)
				*_m.user_attempts = *value.S.(*uuid.UUID)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Attempt.
// This includes values selected through modifiers, order, etc.
func (_m *Attempt) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryQuiz queries the "quiz" edge of the Attempt entity.
func (_m *Attempt) QueryQuiz() *QuizQuery {
	return NewAttemptClient(_m.config).QueryQuiz(_m)
}

// QueryUser queries the "user" edge of the Attempt entity.
func (_m *Attempt) QueryUser() *UserQuery {
	return NewAttemptClient(_m.config).QueryUser(_m)
}

// QueryAttemptAnswers queries the "attempt_answers" edge of the Attempt entity.
func (_m *Attempt) QueryAttemptAnswers() *AttemptAnswerQuery {
	return NewAttemptClient(_m.config).QueryAttemptAnswers(_m)
}

// Update returns a builder for updating this Attempt.
// Note that you need to call Attempt.Unwrap() before calling this method if this Attempt
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Attempt) Update() *AttemptUpdateOne {
	return NewAttemptClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Attempt entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Attempt) Unwrap() *Attempt {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Attempt is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Attempt) String() string {
	var builder strings.Builder
	builder.WriteString("Attempt(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("score=")
	builder.WriteString(fmt.Sprintf("%v", _m.Score))
	builder.WriteString(", ")
	builder.WriteString("total=")
	builder.WriteString(fmt.Sprintf("%v", _m.Total))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Attempts is a parsable slice of Attempt.
type Attempts []*Attempt
