// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"encore.app/ent/answer"
	"encore.app/ent/attempt"
	"encore.app/ent/attemptanswer"
	"encore.app/ent/question"
	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// AttemptAnswer is the model entity for the AttemptAnswer schema.
type AttemptAnswer struct {
	config
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the AttemptAnswerQuery when eager-loading is set.
	Edges                    AttemptAnswerEdges `json:"edges"`
	answer_attempt_answers   *uuid.UUID
	attempt_attempt_answers  *uuid.UUID
	question_attempt_answers *uuid.UUID
	selectValues             sql.SelectValues
}

// AttemptAnswerEdges holds the relations/edges for other nodes in the graph.
type AttemptAnswerEdges struct {
	// Attempt holds the value of the attempt edge.
	Attempt *Attempt `json:"attempt,omitempty"`
	// Question holds the value of the question edge.
	Question *Question `json:"question,omitempty"`
	// Answer holds the value of the answer edge.
	Answer *Answer `json:"answer,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// AttemptOrErr returns the Attempt value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AttemptAnswerEdges) AttemptOrErr() (*Attempt, error) {
	if e.Attempt != nil {
		return e.Attempt, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: attempt.Label}
	}
	return nil, &NotLoadedError{edge: "attempt"}
}

// QuestionOrErr returns the Question value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AttemptAnswerEdges) QuestionOrErr() (*Question, error) {
	if e.Question != nil {
		return e.Question, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: question.Label}
	}
	return nil, &NotLoadedError{edge: "question"}
}

// AnswerOrErr returns the Answer value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AttemptAnswerEdges) AnswerOrErr() (*Answer, error) {
	if e.Answer != nil {
		return e.Answer, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: answer.Label}
	}
	return nil, &NotLoadedError{edge: "answer"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AttemptAnswer) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case attemptanswer.FieldID:
			values[i] = new(uuid.UUID)
		case attemptanswer.ForeignKeys[0]: // answer_attempt_answers
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case attemptanswer.ForeignKeys[1]: // attempt_attempt_answers
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case attemptanswer.ForeignKeys[2]: // question_attempt_answers
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AttemptAnswer fields.
func (_m *AttemptAnswer) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case attemptanswer.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case attemptanswer.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field answer_attempt_answers", values[i])
			} else if value.Valid {
				_m.answer_attempt_answers = new(uuid.UUID)
				*_m.answer_attempt_answers = *value.S.(*uuid.UUID)
			}
		case attemptanswer.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field attempt_attempt_answers", values[i])
			} else if value.Valid {
				_m.attempt_attempt_answers = new(uuid.UUID)
				*_m.attempt_attempt_answers = *value.S.(*uuid.UUID)
			}
		case attemptanswer.ForeignKeys[2]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field question_attempt_answers", values[i])
			} else if value.Valid {
				_m.question_attempt_answers = new(uuid.UUID)
				*_m.question_attempt_answers = *value.S.(*uuid.UUID)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AttemptAnswer.
// This includes values selected through modifiers, order, etc.
func (_m *AttemptAnswer) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryAttempt queries the "attempt" edge of the AttemptAnswer entity.
func (_m *AttemptAnswer) QueryAttempt() *AttemptQuery {
	return NewAttemptAnswerClient(_m.config).QueryAttempt(_m)
}

// QueryQuestion queries the "question" edge of the AttemptAnswer entity.
func (_m *AttemptAnswer) QueryQuestion() *QuestionQuery {
	return NewAttemptAnswerClient(_m.config).QueryQuestion(_m)
}

// QueryAnswer queries the "answer" edge of the AttemptAnswer entity.
func (_m *AttemptAnswer) QueryAnswer() *AnswerQuery {
	return NewAttemptAnswerClient(_m.config).QueryAnswer(_m)
}

// Update returns a builder for updating this AttemptAnswer.
// Note that you need to call AttemptAnswer.Unwrap() before calling this method if this AttemptAnswer
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *AttemptAnswer) Update() *AttemptAnswerUpdateOne {
	return NewAttemptAnswerClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the AttemptAnswer entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *AttemptAnswer) Unwrap() *AttemptAnswer {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: AttemptAnswer is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *AttemptAnswer) String() string {
	var builder strings.Builder
	builder.WriteString("AttemptAnswer(")
	builder.WriteString(fmt.Sprintf("id=%v", _m.ID))
	builder.WriteByte(')')
	return builder.String()
}

// AttemptAnswers is a parsable slice of AttemptAnswer.
type AttemptAnswers []*AttemptAnswer
