// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"encore.app/ent/answer"
	"encore.app/ent/attempt"
	"encore.app/ent/attemptanswer"
	"encore.app/ent/predicate"
	"encore.app/ent/question"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// AttemptAnswerUpdate is the builder for updating AttemptAnswer entities.
type AttemptAnswerUpdate struct {
	config
	hooks    []Hook
	mutation *AttemptAnswerMutation
}

// Where appends a list predicates to the AttemptAnswerUpdate builder.
func (_u *AttemptAnswerUpdate) Where(ps ...predicate.AttemptAnswer) *AttemptAnswerUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetAttemptID sets the "attempt" edge to the Attempt entity by ID.
func (_u *AttemptAnswerUpdate) SetAttemptID(id uuid.UUID) *AttemptAnswerUpdate {
	_u.mutation.SetAttemptID(id)
	return _u
}

// SetNillableAttemptID sets the "attempt" edge to the Attempt entity by ID if the given value is not nil.
func (_u *AttemptAnswerUpdate) SetNillableAttemptID(id *uuid.UUID) *AttemptAnswerUpdate {
	if id != nil {
		_u = _u.SetAttemptID(*id)
	}
	return _u
}

// SetAttempt sets the "attempt" edge to the Attempt entity.
func (_u *AttemptAnswerUpdate) SetAttempt(v *Attempt) *AttemptAnswerUpdate {
	return _u.SetAttemptID(v.ID)
}

// SetQuestionID sets the "question" edge to the Question entity by ID.
func (_u *AttemptAnswerUpdate) SetQuestionID(id uuid.UUID) *AttemptAnswerUpdate {
	_u.mutation.SetQuestionID(id)
	return _u
}

// SetNillableQuestionID sets the "question" edge to the Question entity by ID if the given value is not nil.
func (_u *AttemptAnswerUpdate) SetNillableQuestionID(id *uuid.UUID) *AttemptAnswerUpdate {
	if id != nil {
		_u = _u.SetQuestionID(*id)
	}
	return _u
}

// SetQuestion sets the "question" edge to the Question entity.
func (_u *AttemptAnswerUpdate) SetQuestion(v *Question) *AttemptAnswerUpdate {
	return _u.SetQuestionID(v.ID)
}

// SetAnswerID sets the "answer" edge to the Answer entity by ID.
func (_u *AttemptAnswerUpdate) SetAnswerID(id uuid.UUID) *AttemptAnswerUpdate {
	_u.mutation.SetAnswerID(id)
	return _u
}

// SetNillableAnswerID sets the "answer" edge to the Answer entity by ID if the given value is not nil.
func (_u *AttemptAnswerUpdate) SetNillableAnswerID(id *uuid.UUID) *AttemptAnswerUpdate {
	if id != nil {
		_u = _u.SetAnswerID(*id)
	}
	return _u
}

// SetAnswer sets the "answer" edge to the Answer entity.
func (_u *AttemptAnswerUpdate) SetAnswer(v *Answer) *AttemptAnswerUpdate {
	return _u.SetAnswerID(v.ID)
}

// Mutation returns the AttemptAnswerMutation object of the builder.
func (_u *AttemptAnswerUpdate) Mutation() *AttemptAnswerMutation {
	return _u.mutation
}

// ClearAttempt clears the "attempt" edge to the Attempt entity.
func (_u *AttemptAnswerUpdate) ClearAttempt() *AttemptAnswerUpdate {
	_u.mutation.ClearAttempt()
	return _u
}

// ClearQuestion clears the "question" edge to the Question entity.
func (_u *AttemptAnswerUpdate) ClearQuestion() *AttemptAnswerUpdate {
	_u.mutation.ClearQuestion()
	return _u
}

// ClearAnswer clears the "answer" edge to the Answer entity.
func (_u *AttemptAnswerUpdate) ClearAnswer() *AttemptAnswerUpdate {
	_u.mutation.ClearAnswer()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AttemptAnswerUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AttemptAnswerUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AttemptAnswerUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AttemptAnswerUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *AttemptAnswerUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(attemptanswer.Table, attemptanswer.Columns, sqlgraph.NewFieldSpec(attemptanswer.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.AttemptCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   attemptanswer.AttemptTable,
			Columns: []string{attemptanswer.AttemptColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(attempt.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AttemptIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   attemptanswer.AttemptTable,
			Columns: []string{attemptanswer.AttemptColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(attempt.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.QuestionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   attemptanswer.QuestionTable,
			Columns: []string{attemptanswer.QuestionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(question.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.QuestionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   attemptanswer.QuestionTable,
			Columns: []string{attemptanswer.QuestionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(question.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AnswerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   attemptanswer.AnswerTable,
			Columns: []string{attemptanswer.AnswerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(answer.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AnswerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   attemptanswer.AnswerTable,
			Columns: []string{attemptanswer.AnswerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(answer.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{attemptanswer.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AttemptAnswerUpdateOne is the builder for updating a single AttemptAnswer entity.
type AttemptAnswerUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AttemptAnswerMutation
}

// SetAttemptID sets the "attempt" edge to the Attempt entity by ID.
func (_u *AttemptAnswerUpdateOne) SetAttemptID(id uuid.UUID) *AttemptAnswerUpdateOne {
	_u.mutation.SetAttemptID(id)
	return _u
}

// SetNillableAttemptID sets the "attempt" edge to the Attempt entity by ID if the given value is not nil.
func (_u *AttemptAnswerUpdateOne) SetNillableAttemptID(id *uuid.UUID) *AttemptAnswerUpdateOne {
	if id != nil {
		_u = _u.SetAttemptID(*id)
	}
	return _u
}

// SetAttempt sets the "attempt" edge to the Attempt entity.
func (_u *AttemptAnswerUpdateOne) SetAttempt(v *Attempt) *AttemptAnswerUpdateOne {
	return _u.SetAttemptID(v.ID)
}

// SetQuestionID sets the "question" edge to the Question entity by ID.
func (_u *AttemptAnswerUpdateOne) SetQuestionID(id uuid.UUID) *AttemptAnswerUpdateOne {
	_u.mutation.SetQuestionID(id)
	return _u
}

// SetNillableQuestionID sets the "question" edge to the Question entity by ID if the given value is not nil.
func (_u *AttemptAnswerUpdateOne) SetNillableQuestionID(id *uuid.UUID) *AttemptAnswerUpdateOne {
	if id != nil {
		_u = _u.SetQuestionID(*id)
	}
	return _u
}

// SetQuestion sets the "question" edge to the Question entity.
func (_u *AttemptAnswerUpdateOne) SetQuestion(v *Question) *AttemptAnswerUpdateOne {
	return _u.SetQuestionID(v.ID)
}

// SetAnswerID sets the "answer" edge to the Answer entity by ID.
func (_u *AttemptAnswerUpdateOne) SetAnswerID(id uuid.UUID) *AttemptAnswerUpdateOne {
	_u.mutation.SetAnswerID(id)
	return _u
}

// SetNillableAnswerID sets the "answer" edge to the Answer entity by ID if the given value is not nil.
func (_u *AttemptAnswerUpdateOne) SetNillableAnswerID(id *uuid.UUID) *AttemptAnswerUpdateOne {
	if id != nil {
		_u = _u.SetAnswerID(*id)
	}
	return _u
}

// SetAnswer sets the "answer" edge to the Answer entity.
func (_u *AttemptAnswerUpdateOne) SetAnswer(v *Answer) *AttemptAnswerUpdateOne {
	return _u.SetAnswerID(v.ID)
}

// Mutation returns the AttemptAnswerMutation object of the builder.
func (_u *AttemptAnswerUpdateOne) Mutation() *AttemptAnswerMutation {
	return _u.mutation
}

// ClearAttempt clears the "attempt" edge to the Attempt entity.
func (_u *AttemptAnswerUpdateOne) ClearAttempt() *AttemptAnswerUpdateOne {
	_u.mutation.ClearAttempt()
	return _u
}

// ClearQuestion clears the "question" edge to the Question entity.
func (_u *AttemptAnswerUpdateOne) ClearQuestion() *AttemptAnswerUpdateOne {
	_u.mutation.ClearQuestion()
	return _u
}

// ClearAnswer clears the "answer" edge to the Answer entity.
func (_u *AttemptAnswerUpdateOne) ClearAnswer() *AttemptAnswerUpdateOne {
	_u.mutation.ClearAnswer()
	return _u
}

// Where appends a list predicates to the AttemptAnswerUpdate builder.
func (_u *AttemptAnswerUpdateOne) Where(ps ...predicate.AttemptAnswer) *AttemptAnswerUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AttemptAnswerUpdateOne) Select(field string, fields ...string) *AttemptAnswerUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AttemptAnswer entity.
func (_u *AttemptAnswerUpdateOne) Save(ctx context.Context) (*AttemptAnswer, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AttemptAnswerUpdateOne) SaveX(ctx context.Context) *AttemptAnswer {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AttemptAnswerUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AttemptAnswerUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *AttemptAnswerUpdateOne) sqlSave(ctx context.Context) (_node *AttemptAnswer, err error) {
	_spec := sqlgraph.NewUpdateSpec(attemptanswer.Table, attemptanswer.Columns, sqlgraph.NewFieldSpec(attemptanswer.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AttemptAnswer.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, attemptanswer.FieldID)
		for _, f := range fields {
			if !attemptanswer.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != attemptanswer.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.AttemptCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   attemptanswer.AttemptTable,
			Columns: []string{attemptanswer.AttemptColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(attempt.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AttemptIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   attemptanswer.AttemptTable,
			Columns: []string{attemptanswer.AttemptColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(attempt.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.QuestionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   attemptanswer.QuestionTable,
			Columns: []string{attemptanswer.QuestionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(question.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.QuestionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   attemptanswer.QuestionTable,
			Columns: []string{attemptanswer.QuestionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(question.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AnswerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   attemptanswer.AnswerTable,
			Columns: []string{attemptanswer.AnswerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(answer.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AnswerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   attemptanswer.AnswerTable,
			Columns: []string{attemptanswer.AnswerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(answer.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &AttemptAnswer{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{attemptanswer.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
