// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"encore.app/ent/attemptanswer"
	"encore.app/ent/predicate"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AttemptAnswerDelete is the builder for deleting a AttemptAnswer entity.
type AttemptAnswerDelete struct {
	config
	hooks    []Hook
	mutation *AttemptAnswerMutation
}

// Where appends a list predicates to the AttemptAnswerDelete builder.
func (_d *AttemptAnswerDelete) Where(ps ...predicate.AttemptAnswer) *AttemptAnswerDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *AttemptAnswerDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AttemptAnswerDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *AttemptAnswerDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(attemptanswer.Table, sqlgraph.NewFieldSpec(attemptanswer.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// AttemptAnswerDeleteOne is the builder for deleting a single AttemptAnswer entity.
type AttemptAnswerDeleteOne struct {
	_d *AttemptAnswerDelete
}

// Where appends a list predicates to the AttemptAnswerDelete builder.
func (_d *AttemptAnswerDeleteOne) Where(ps ...predicate.AttemptAnswer) *AttemptAnswerDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *AttemptAnswerDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{attemptanswer.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AttemptAnswerDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
