// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"encore.app/ent/answer"
	"encore.app/ent/attempt"
	"encore.app/ent/attemptanswer"
	"encore.app/ent/predicate"
	"encore.app/ent/question"
	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// AttemptAnswerQuery is the builder for querying AttemptAnswer entities.
type AttemptAnswerQuery struct {
	config
	ctx          *QueryContext
	order        []attemptanswer.OrderOption
	inters       []Interceptor
	predicates   []predicate.AttemptAnswer
	withAttempt  *AttemptQuery
	withQuestion *QuestionQuery
	withAnswer   *AnswerQuery
	withFKs      bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the AttemptAnswerQuery builder.
func (_q *AttemptAnswerQuery) Where(ps ...predicate.AttemptAnswer) *AttemptAnswerQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *AttemptAnswerQuery) Limit(limit int) *AttemptAnswerQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *AttemptAnswerQuery) Offset(offset int) *AttemptAnswerQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *AttemptAnswerQuery) Unique(unique bool) *AttemptAnswerQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *AttemptAnswerQuery) Order(o ...attemptanswer.OrderOption) *AttemptAnswerQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryAttempt chains the current query on the "attempt" edge.
func (_q *AttemptAnswerQuery) QueryAttempt() *AttemptQuery {
	query := (&AttemptClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(attemptanswer.Table, attemptanswer.FieldID, selector),
			sqlgraph.To(attempt.Table, attempt.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, attemptanswer.AttemptTable, attemptanswer.AttemptColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryQuestion chains the current query on the "question" edge.
func (_q *AttemptAnswerQuery) QueryQuestion() *QuestionQuery {
	query := (&QuestionClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(attemptanswer.Table, attemptanswer.FieldID, selector),
			sqlgraph.To(question.Table, question.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, attemptanswer.QuestionTable, attemptanswer.QuestionColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryAnswer chains the current query on the "answer" edge.
func (_q *AttemptAnswerQuery) QueryAnswer() *AnswerQuery {
	query := (&AnswerClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(attemptanswer.Table, attemptanswer.FieldID, selector),
			sqlgraph.To(answer.Table, answer.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, attemptanswer.AnswerTable, attemptanswer.AnswerColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first AttemptAnswer entity from the query.
// Returns a *NotFoundError when no AttemptAnswer was found.
func (_q *AttemptAnswerQuery) First(ctx context.Context) (*AttemptAnswer, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{attemptanswer.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *AttemptAnswerQuery) FirstX(ctx context.Context) *AttemptAnswer {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first AttemptAnswer ID from the query.
// Returns a *NotFoundError when no AttemptAnswer ID was found.
func (_q *AttemptAnswerQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{attemptanswer.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *AttemptAnswerQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single AttemptAnswer entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one AttemptAnswer entity is found.
// Returns a *NotFoundError when no AttemptAnswer entities are found.
func (_q *AttemptAnswerQuery) Only(ctx context.Context) (*AttemptAnswer, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{attemptanswer.Label}
	default:
		return nil, &NotSingularError{attemptanswer.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *AttemptAnswerQuery) OnlyX(ctx context.Context) *AttemptAnswer {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only AttemptAnswer ID in the query.
// Returns a *NotSingularError when more than one AttemptAnswer ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *AttemptAnswerQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{attemptanswer.Label}
	default:
		err = &NotSingularError{attemptanswer.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *AttemptAnswerQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of AttemptAnswers.
func (_q *AttemptAnswerQuery) All(ctx context.Context) ([]*AttemptAnswer, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*AttemptAnswer, *AttemptAnswerQuery]()
	return withInterceptors[[]*AttemptAnswer](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *AttemptAnswerQuery) AllX(ctx context.Context) []*AttemptAnswer {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of AttemptAnswer IDs.
func (_q *AttemptAnswerQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(attemptanswer.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *AttemptAnswerQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *AttemptAnswerQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*AttemptAnswerQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *AttemptAnswerQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *AttemptAnswerQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *AttemptAnswerQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the AttemptAnswerQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *AttemptAnswerQuery) Clone() *AttemptAnswerQuery {
	if _q == nil {
		return nil
	}
	return &AttemptAnswerQuery{
		config:       _q.config,
		ctx:          _q.ctx.Clone(),
		order:        append([]attemptanswer.OrderOption{}, _q.order...),
		inters:       append([]Interceptor{}, _q.inters...),
		predicates:   append([]predicate.AttemptAnswer{}, _q.predicates...),
		withAttempt:  _q.withAttempt.Clone(),
		withQuestion: _q.withQuestion.Clone(),
		withAnswer:   _q.withAnswer.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithAttempt tells the query-builder to eager-load the nodes that are connected to
// the "attempt" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *AttemptAnswerQuery) WithAttempt(opts ...func(*AttemptQuery)) *AttemptAnswerQuery {
	query := (&AttemptClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withAttempt = query
	return _q
}

// WithQuestion tells the query-builder to eager-load the nodes that are connected to
// the "question" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *AttemptAnswerQuery) WithQuestion(opts ...func(*QuestionQuery)) *AttemptAnswerQuery {
	query := (&QuestionClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withQuestion = query
	return _q
}

// WithAnswer tells the query-builder to eager-load the nodes that are connected to
// the "answer" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *AttemptAnswerQuery) WithAnswer(opts ...func(*AnswerQuery)) *AttemptAnswerQuery {
	query := (&AnswerClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withAnswer = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
func (_q *AttemptAnswerQuery) GroupBy(field string, fields ...string) *AttemptAnswerGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &AttemptAnswerGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = attemptanswer.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
func (_q *AttemptAnswerQuery) Select(fields ...string) *AttemptAnswerSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &AttemptAnswerSelect{AttemptAnswerQuery: _q}
	sbuild.label = attemptanswer.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a AttemptAnswerSelect configured with the given aggregations.
func (_q *AttemptAnswerQuery) Aggregate(fns ...AggregateFunc) *AttemptAnswerSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *AttemptAnswerQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !attemptanswer.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *AttemptAnswerQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*AttemptAnswer, error) {
	var (
		nodes       = []*AttemptAnswer{}
		withFKs     = _q.withFKs
		_spec       = _q.querySpec()
		loadedTypes = [3]bool{
			_q.withAttempt != nil,
			_q.withQuestion != nil,
			_q.withAnswer != nil,
		}
	)
	if _q.withAttempt != nil || _q.withQuestion != nil || _q.withAnswer != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, attemptanswer.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*AttemptAnswer).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &AttemptAnswer{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withAttempt; query != nil {
		if err := _q.loadAttempt(ctx, query, nodes, nil,
			func(n *AttemptAnswer, e *Attempt) { n.Edges.Attempt = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withQuestion; query != nil {
		if err := _q.loadQuestion(ctx, query, nodes, nil,
			func(n *AttemptAnswer, e *Question) { n.Edges.Question = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withAnswer; query != nil {
		if err := _q.loadAnswer(ctx, query, nodes, nil,
			func(n *AttemptAnswer, e *Answer) { n.Edges.Answer = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *AttemptAnswerQuery) loadAttempt(ctx context.Context, query *AttemptQuery, nodes []*AttemptAnswer, init func(*AttemptAnswer), assign func(*AttemptAnswer, *Attempt)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*AttemptAnswer)
	for i := range nodes {
		if nodes[i].attempt_attempt_answers == nil {
			continue
		}
		fk := *nodes[i].attempt_attempt_answers
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(attempt.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "attempt_attempt_answers" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *AttemptAnswerQuery) loadQuestion(ctx context.Context, query *QuestionQuery, nodes []*AttemptAnswer, init func(*AttemptAnswer), assign func(*AttemptAnswer, *Question)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*AttemptAnswer)
	for i := range nodes {
		if nodes[i].question_attempt_answers == nil {
			continue
		}
		fk := *nodes[i].question_attempt_answers
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(question.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "question_attempt_answers" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *AttemptAnswerQuery) loadAnswer(ctx context.Context, query *AnswerQuery, nodes []*AttemptAnswer, init func(*AttemptAnswer), assign func(*AttemptAnswer, *Answer)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*AttemptAnswer)
	for i := range nodes {
		if nodes[i].answer_attempt_answers == nil {
			continue
		}
		fk := *nodes[i].answer_attempt_answers
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(answer.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "answer_attempt_answers" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *AttemptAnswerQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *AttemptAnswerQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(attemptanswer.Table, attemptanswer.Columns, sqlgraph.NewFieldSpec(attemptanswer.FieldID, field.TypeUUID))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, attemptanswer.FieldID)
		for i := range fields {
			if fields[i] != attemptanswer.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *AttemptAnswerQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(attemptanswer.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = attemptanswer.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// AttemptAnswerGroupBy is the group-by builder for AttemptAnswer entities.
type AttemptAnswerGroupBy struct {
	selector
	build *AttemptAnswerQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *AttemptAnswerGroupBy) Aggregate(fns ...AggregateFunc) *AttemptAnswerGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *AttemptAnswerGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*AttemptAnswerQuery, *AttemptAnswerGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *AttemptAnswerGroupBy) sqlScan(ctx context.Context, root *AttemptAnswerQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// AttemptAnswerSelect is the builder for selecting fields of AttemptAnswer entities.
type AttemptAnswerSelect struct {
	*AttemptAnswerQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *AttemptAnswerSelect) Aggregate(fns ...AggregateFunc) *AttemptAnswerSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *AttemptAnswerSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*AttemptAnswerQuery, *AttemptAnswerSelect](ctx, _s.AttemptAnswerQuery, _s, _s.inters, v)
}

func (_s *AttemptAnswerSelect) sqlScan(ctx context.Context, root *AttemptAnswerQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
