// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"encore.app/ent/answer"
	"encore.app/ent/attempt"
	"encore.app/ent/attemptanswer"
	"encore.app/ent/question"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// AttemptAnswerCreate is the builder for creating a AttemptAnswer entity.
type AttemptAnswerCreate struct {
	config
	mutation *AttemptAnswerMutation
	hooks    []Hook
}

// SetID sets the "id" field.
func (_c *AttemptAnswerCreate) SetID(v uuid.UUID) *AttemptAnswerCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *AttemptAnswerCreate) SetNillableID(v *uuid.UUID) *AttemptAnswerCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetAttemptID sets the "attempt" edge to the Attempt entity by ID.
func (_c *AttemptAnswerCreate) SetAttemptID(id uuid.UUID) *AttemptAnswerCreate {
	_c.mutation.SetAttemptID(id)
	return _c
}

// SetNillableAttemptID sets the "attempt" edge to the Attempt entity by ID if the given value is not nil.
func (_c *AttemptAnswerCreate) SetNillableAttemptID(id *uuid.UUID) *AttemptAnswerCreate {
	if id != nil {
		_c = _c.SetAttemptID(*id)
	}
	return _c
}

// SetAttempt sets the "attempt" edge to the Attempt entity.
func (_c *AttemptAnswerCreate) SetAttempt(v *Attempt) *AttemptAnswerCreate {
	return _c.SetAttemptID(v.ID)
}

// SetQuestionID sets the "question" edge to the Question entity by ID.
func (_c *AttemptAnswerCreate) SetQuestionID(id uuid.UUID) *AttemptAnswerCreate {
	_c.mutation.SetQuestionID(id)
	return _c
}

// SetNillableQuestionID sets the "question" edge to the Question entity by ID if the given value is not nil.
func (_c *AttemptAnswerCreate) SetNillableQuestionID(id *uuid.UUID) *AttemptAnswerCreate {
	if id != nil {
		_c = _c.SetQuestionID(*id)
	}
	return _c
}

// SetQuestion sets the "question" edge to the Question entity.
func (_c *AttemptAnswerCreate) SetQuestion(v *Question) *AttemptAnswerCreate {
	return _c.SetQuestionID(v.ID)
}

// SetAnswerID sets the "answer" edge to the Answer entity by ID.
func (_c *AttemptAnswerCreate) SetAnswerID(id uuid.UUID) *AttemptAnswerCreate {
	_c.mutation.SetAnswerID(id)
	return _c
}

// SetNillableAnswerID sets the "answer" edge to the Answer entity by ID if the given value is not nil.
func (_c *AttemptAnswerCreate) SetNillableAnswerID(id *uuid.UUID) *AttemptAnswerCreate {
	if id != nil {
		_c = _c.SetAnswerID(*id)
	}
	return _c
}

// SetAnswer sets the "answer" edge to the Answer entity.
func (_c *AttemptAnswerCreate) SetAnswer(v *Answer) *AttemptAnswerCreate {
	return _c.SetAnswerID(v.ID)
}

// Mutation returns the AttemptAnswerMutation object of the builder.
func (_c *AttemptAnswerCreate) Mutation() *AttemptAnswerMutation {
	return _c.mutation
}

// Save creates the AttemptAnswer in the database.
func (_c *AttemptAnswerCreate) Save(ctx context.Context) (*AttemptAnswer, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AttemptAnswerCreate) SaveX(ctx context.Context) *AttemptAnswer {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AttemptAnswerCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AttemptAnswerCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AttemptAnswerCreate) defaults() {
	if _, ok := _c.mutation.ID(); !ok {
		v := attemptanswer.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AttemptAnswerCreate) check() error {
	return nil
}

func (_c *AttemptAnswerCreate) sqlSave(ctx context.Context) (*AttemptAnswer, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AttemptAnswerCreate) createSpec() (*AttemptAnswer, *sqlgraph.CreateSpec) {
	var (
		_node = &AttemptAnswer{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(attemptanswer.Table, sqlgraph.NewFieldSpec(attemptanswer.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if nodes := _c.mutation.AttemptIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   attemptanswer.AttemptTable,
			Columns: []string{attemptanswer.AttemptColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(attempt.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.attempt_attempt_answers = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.QuestionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   attemptanswer.QuestionTable,
			Columns: []string{attemptanswer.QuestionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(question.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.question_attempt_answers = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.AnswerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   attemptanswer.AnswerTable,
			Columns: []string{attemptanswer.AnswerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(answer.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.answer_attempt_answers = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// AttemptAnswerCreateBulk is the builder for creating many AttemptAnswer entities in bulk.
type AttemptAnswerCreateBulk struct {
	config
	err      error
	builders []*AttemptAnswerCreate
}

// Save creates the AttemptAnswer entities in the database.
func (_c *AttemptAnswerCreateBulk) Save(ctx context.Context) ([]*AttemptAnswer, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AttemptAnswer, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AttemptAnswerMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AttemptAnswerCreateBulk) SaveX(ctx context.Context) []*AttemptAnswer {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AttemptAnswerCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AttemptAnswerCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
