// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"encore.app/ent/answer"
	"encore.app/ent/attemptanswer"
	"encore.app/ent/predicate"
	"encore.app/ent/question"
	"encore.app/ent/quiz"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// QuestionUpdate is the builder for updating Question entities.
type QuestionUpdate struct {
	config
	hooks    []Hook
	mutation *QuestionMutation
}

// Where appends a list predicates to the QuestionUpdate builder.
func (_u *QuestionUpdate) Where(ps ...predicate.Question) *QuestionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetText sets the "text" field.
func (_u *QuestionUpdate) SetText(v string) *QuestionUpdate {
	_u.mutation.SetText(v)
	return _u
}

// SetNillableText sets the "text" field if the given value is not nil.
func (_u *QuestionUpdate) SetNillableText(v *string) *QuestionUpdate {
	if v != nil {
		_u.SetText(*v)
	}
	return _u
}

// SetOrderIndex sets the "order_index" field.
func (_u *QuestionUpdate) SetOrderIndex(v int) *QuestionUpdate {
	_u.mutation.ResetOrderIndex()
	_u.mutation.SetOrderIndex(v)
	return _u
}

// SetNillableOrderIndex sets the "order_index" field if the given value is not nil.
func (_u *QuestionUpdate) SetNillableOrderIndex(v *int) *QuestionUpdate {
	if v != nil {
		_u.SetOrderIndex(*v)
	}
	return _u
}

// AddOrderIndex adds value to the "order_index" field.
func (_u *QuestionUpdate) AddOrderIndex(v int) *QuestionUpdate {
	_u.mutation.AddOrderIndex(v)
	return _u
}

// SetQuizID sets the "quiz" edge to the Quiz entity by ID.
func (_u *QuestionUpdate) SetQuizID(id uuid.UUID) *QuestionUpdate {
	_u.mutation.SetQuizID(id)
	return _u
}

// SetNillableQuizID sets the "quiz" edge to the Quiz entity by ID if the given value is not nil.
func (_u *QuestionUpdate) SetNillableQuizID(id *uuid.UUID) *QuestionUpdate {
	if id != nil {
		_u = _u.SetQuizID(*id)
	}
	return _u
}

// SetQuiz sets the "quiz" edge to the Quiz entity.
func (_u *QuestionUpdate) SetQuiz(v *Quiz) *QuestionUpdate {
	return _u.SetQuizID(v.ID)
}

// AddAnswerIDs adds the "answers" edge to the Answer entity by IDs.
func (_u *QuestionUpdate) AddAnswerIDs(ids ...uuid.UUID) *QuestionUpdate {
	_u.mutation.AddAnswerIDs(ids...)
	return _u
}

// AddAnswers adds the "answers" edges to the Answer entity.
func (_u *QuestionUpdate) AddAnswers(v ...*Answer) *QuestionUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAnswerIDs(ids...)
}

// AddAttemptAnswerIDs adds the "attempt_answers" edge to the AttemptAnswer entity by IDs.
func (_u *QuestionUpdate) AddAttemptAnswerIDs(ids ...uuid.UUID) *QuestionUpdate {
	_u.mutation.AddAttemptAnswerIDs(ids...)
	return _u
}

// AddAttemptAnswers adds the "attempt_answers" edges to the AttemptAnswer entity.
func (_u *QuestionUpdate) AddAttemptAnswers(v ...*AttemptAnswer) *QuestionUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAttemptAnswerIDs(ids...)
}

// Mutation returns the QuestionMutation object of the builder.
func (_u *QuestionUpdate) Mutation() *QuestionMutation {
	return _u.mutation
}

// ClearQuiz clears the "quiz" edge to the Quiz entity.
func (_u *QuestionUpdate) ClearQuiz() *QuestionUpdate {
	_u.mutation.ClearQuiz()
	return _u
}

// ClearAnswers clears all "answers" edges to the Answer entity.
func (_u *QuestionUpdate) ClearAnswers() *QuestionUpdate {
	_u.mutation.ClearAnswers()
	return _u
}

// RemoveAnswerIDs removes the "answers" edge to Answer entities by IDs.
func (_u *QuestionUpdate) RemoveAnswerIDs(ids ...uuid.UUID) *QuestionUpdate {
	_u.mutation.RemoveAnswerIDs(ids...)
	return _u
}

// RemoveAnswers removes "answers" edges to Answer entities.
func (_u *QuestionUpdate) RemoveAnswers(v ...*Answer) *QuestionUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAnswerIDs(ids...)
}

// ClearAttemptAnswers clears all "attempt_answers" edges to the AttemptAnswer entity.
func (_u *QuestionUpdate) ClearAttemptAnswers() *QuestionUpdate {
	_u.mutation.ClearAttemptAnswers()
	return _u
}

// RemoveAttemptAnswerIDs removes the "attempt_answers" edge to AttemptAnswer entities by IDs.
func (_u *QuestionUpdate) RemoveAttemptAnswerIDs(ids ...uuid.UUID) *QuestionUpdate {
	_u.mutation.RemoveAttemptAnswerIDs(ids...)
	return _u
}

// RemoveAttemptAnswers removes "attempt_answers" edges to AttemptAnswer entities.
func (_u *QuestionUpdate) RemoveAttemptAnswers(v ...*AttemptAnswer) *QuestionUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAttemptAnswerIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *QuestionUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *QuestionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *QuestionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *QuestionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *QuestionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(question.Table, question.Columns, sqlgraph.NewFieldSpec(question.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Text(); ok {
		_spec.SetField(question.FieldText, field.TypeString, value)
	}
	if value, ok := _u.mutation.OrderIndex(); ok {
		_spec.SetField(question.FieldOrderIndex, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedOrderIndex(); ok {
		_spec.AddField(question.FieldOrderIndex, field.TypeInt, value)
	}
	if _u.mutation.QuizCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   question.QuizTable,
			Columns: []string{question.QuizColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(quiz.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.QuizIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   question.QuizTable,
			Columns: []string{question.QuizColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(quiz.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AnswersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   question.AnswersTable,
			Columns: []string{question.AnswersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(answer.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAnswersIDs(); len(nodes) > 0 && !_u.mutation.AnswersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   question.AnswersTable,
			Columns: []string{question.AnswersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(answer.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AnswersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   question.AnswersTable,
			Columns: []string{question.AnswersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(answer.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AttemptAnswersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   question.AttemptAnswersTable,
			Columns: []string{question.AttemptAnswersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(attemptanswer.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAttemptAnswersIDs(); len(nodes) > 0 && !_u.mutation.AttemptAnswersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   question.AttemptAnswersTable,
			Columns: []string{question.AttemptAnswersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(attemptanswer.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AttemptAnswersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   question.AttemptAnswersTable,
			Columns: []string{question.AttemptAnswersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(attemptanswer.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{question.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// QuestionUpdateOne is the builder for updating a single Question entity.
type QuestionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *QuestionMutation
}

// SetText sets the "text" field.
func (_u *QuestionUpdateOne) SetText(v string) *QuestionUpdateOne {
	_u.mutation.SetText(v)
	return _u
}

// SetNillableText sets the "text" field if the given value is not nil.
func (_u *QuestionUpdateOne) SetNillableText(v *string) *QuestionUpdateOne {
	if v != nil {
		_u.SetText(*v)
	}
	return _u
}

// SetOrderIndex sets the "order_index" field.
func (_u *QuestionUpdateOne) SetOrderIndex(v int) *QuestionUpdateOne {
	_u.mutation.ResetOrderIndex()
	_u.mutation.SetOrderIndex(v)
	return _u
}

// SetNillableOrderIndex sets the "order_index" field if the given value is not nil.
func (_u *QuestionUpdateOne) SetNillableOrderIndex(v *int) *QuestionUpdateOne {
	if v != nil {
		_u.SetOrderIndex(*v)
	}
	return _u
}

// AddOrderIndex adds value to the "order_index" field.
func (_u *QuestionUpdateOne) AddOrderIndex(v int) *QuestionUpdateOne {
	_u.mutation.AddOrderIndex(v)
	return _u
}

// SetQuizID sets the "quiz" edge to the Quiz entity by ID.
func (_u *QuestionUpdateOne) SetQuizID(id uuid.UUID) *QuestionUpdateOne {
	_u.mutation.SetQuizID(id)
	return _u
}

// SetNillableQuizID sets the "quiz" edge to the Quiz entity by ID if the given value is not nil.
func (_u *QuestionUpdateOne) SetNillableQuizID(id *uuid.UUID) *QuestionUpdateOne {
	if id != nil {
		_u = _u.SetQuizID(*id)
	}
	return _u
}

// SetQuiz sets the "quiz" edge to the Quiz entity.
func (_u *QuestionUpdateOne) SetQuiz(v *Quiz) *QuestionUpdateOne {
	return _u.SetQuizID(v.ID)
}

// AddAnswerIDs adds the "answers" edge to the Answer entity by IDs.
func (_u *QuestionUpdateOne) AddAnswerIDs(ids ...uuid.UUID) *QuestionUpdateOne {
	_u.mutation.AddAnswerIDs(ids...)
	return _u
}

// AddAnswers adds the "answers" edges to the Answer entity.
func (_u *QuestionUpdateOne) AddAnswers(v ...*Answer) *QuestionUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAnswerIDs(ids...)
}

// AddAttemptAnswerIDs adds the "attempt_answers" edge to the AttemptAnswer entity by IDs.
func (_u *QuestionUpdateOne) AddAttemptAnswerIDs(ids ...uuid.UUID) *QuestionUpdateOne {
	_u.mutation.AddAttemptAnswerIDs(ids...)
	return _u
}

// AddAttemptAnswers adds the "attempt_answers" edges to the AttemptAnswer entity.
func (_u *QuestionUpdateOne) AddAttemptAnswers(v ...*AttemptAnswer) *QuestionUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAttemptAnswerIDs(ids...)
}

// Mutation returns the QuestionMutation object of the builder.
func (_u *QuestionUpdateOne) Mutation() *QuestionMutation {
	return _u.mutation
}

// ClearQuiz clears the "quiz" edge to the Quiz entity.
func (_u *QuestionUpdateOne) ClearQuiz() *QuestionUpdateOne {
	_u.mutation.ClearQuiz()
	return _u
}

// ClearAnswers clears all "answers" edges to the Answer entity.
func (_u *QuestionUpdateOne) ClearAnswers() *QuestionUpdateOne {
	_u.mutation.ClearAnswers()
	return _u
}

// RemoveAnswerIDs removes the "answers" edge to Answer entities by IDs.
func (_u *QuestionUpdateOne) RemoveAnswerIDs(ids ...uuid.UUID) *QuestionUpdateOne {
	_u.mutation.RemoveAnswerIDs(ids...)
	return _u
}

// RemoveAnswers removes "answers" edges to Answer entities.
func (_u *QuestionUpdateOne) RemoveAnswers(v ...*Answer) *QuestionUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAnswerIDs(ids...)
}

// ClearAttemptAnswers clears all "attempt_answers" edges to the AttemptAnswer entity.
func (_u *QuestionUpdateOne) ClearAttemptAnswers() *QuestionUpdateOne {
	_u.mutation.ClearAttemptAnswers()
	return _u
}

// RemoveAttemptAnswerIDs removes the "attempt_answers" edge to AttemptAnswer entities by IDs.
func (_u *QuestionUpdateOne) RemoveAttemptAnswerIDs(ids ...uuid.UUID) *QuestionUpdateOne {
	_u.mutation.RemoveAttemptAnswerIDs(ids...)
	return _u
}

// RemoveAttemptAnswers removes "attempt_answers" edges to AttemptAnswer entities.
func (_u *QuestionUpdateOne) RemoveAttemptAnswers(v ...*AttemptAnswer) *QuestionUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAttemptAnswerIDs(ids...)
}

// Where appends a list predicates to the QuestionUpdate builder.
func (_u *QuestionUpdateOne) Where(ps ...predicate.Question) *QuestionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *QuestionUpdateOne) Select(field string, fields ...string) *QuestionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Question entity.
func (_u *QuestionUpdateOne) Save(ctx context.Context) (*Question, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *QuestionUpdateOne) SaveX(ctx context.Context) *Question {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *QuestionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *QuestionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *QuestionUpdateOne) sqlSave(ctx context.Context) (_node *Question, err error) {
	_spec := sqlgraph.NewUpdateSpec(question.Table, question.Columns, sqlgraph.NewFieldSpec(question.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Question.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, question.FieldID)
		for _, f := range fields {
			if !question.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != question.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Text(); ok {
		_spec.SetField(question.FieldText, field.TypeString, value)
	}
	if value, ok := _u.mutation.OrderIndex(); ok {
		_spec.SetField(question.FieldOrderIndex, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedOrderIndex(); ok {
		_spec.AddField(question.FieldOrderIndex, field.TypeInt, value)
	}
	if _u.mutation.QuizCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   question.QuizTable,
			Columns: []string{question.QuizColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(quiz.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.QuizIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   question.QuizTable,
			Columns: []string{question.QuizColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(quiz.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AnswersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   question.AnswersTable,
			Columns: []string{question.AnswersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(answer.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAnswersIDs(); len(nodes) > 0 && !_u.mutation.AnswersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   question.AnswersTable,
			Columns: []string{question.AnswersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(answer.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AnswersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   question.AnswersTable,
			Columns: []string{question.AnswersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(answer.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AttemptAnswersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   question.AttemptAnswersTable,
			Columns: []string{question.AttemptAnswersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(attemptanswer.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAttemptAnswersIDs(); len(nodes) > 0 && !_u.mutation.AttemptAnswersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   question.AttemptAnswersTable,
			Columns: []string{question.AttemptAnswersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(attemptanswer.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AttemptAnswersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   question.AttemptAnswersTable,
			Columns: []string{question.AttemptAnswersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(attemptanswer.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Question{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{question.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
