// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"encore.app/ent/question"
	"encore.app/ent/quiz"
	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// Question is the model entity for the Question schema.
type Question struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Text holds the value of the "text" field.
	Text string `json:"text,omitempty"`
	// OrderIndex holds the value of the "order_index" field.
	OrderIndex int `json:"order_index,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the QuestionQuery when eager-loading is set.
	Edges          QuestionEdges `json:"edges"`
	quiz_questions *uuid.UUID
	selectValues   sql.SelectValues
}

// QuestionEdges holds the relations/edges for other nodes in the graph.
type QuestionEdges struct {
	// Quiz holds the value of the quiz edge.
	Quiz *Quiz `json:"quiz,omitempty"`
	// Answers holds the value of the answers edge.
	Answers []*Answer `json:"answers,omitempty"`
	// AttemptAnswers holds the value of the attempt_answers edge.
	AttemptAnswers []*AttemptAnswer `json:"attempt_answers,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// QuizOrErr returns the Quiz value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e QuestionEdges) QuizOrErr() (*Quiz, error) {
	if e.Quiz != nil {
		return e.Quiz, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: quiz.Label}
	}
	return nil, &NotLoadedError{edge: "quiz"}
}

// AnswersOrErr returns the Answers value or an error if the edge
// was not loaded in eager-loading.
func (e QuestionEdges) AnswersOrErr() ([]*Answer, error) {
	if e.loadedTypes[1] {
		return e.Answers, nil
	}
	return nil, &NotLoadedError{edge: "answers"}
}

// AttemptAnswersOrErr returns the AttemptAnswers value or an error if the edge
// was not loaded in eager-loading.
func (e QuestionEdges) AttemptAnswersOrErr() ([]*AttemptAnswer, error) {
	if e.loadedTypes[2] {
		return e.AttemptAnswers, nil
	}
	return nil, &NotLoadedError{edge: "attempt_answers"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Question) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case question.FieldOrderIndex:
			values[i] = new(sql.NullInt64)
		case question.FieldText:
			values[i] = new(sql.NullString)
		case question.FieldID:
			values[i] = new(uuid.UUID)
		case question.ForeignKeys[0]: // quiz_questions
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Question fields.
func (_m *Question) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case question.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case question.FieldText:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field text", values[i])
			} else if value.Valid {
				_m.Text = value.String
			}
		case question.FieldOrderIndex:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field order_index", values[i])
			} else if value.Valid {
				_m.OrderIndex = int(value.Int64)
			}
		case question.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field quiz_questions", values[i])
			} else if value.Valid {
				_m.quiz_questions = new(uuid.UUID)
				*_m.quiz_questions = *value.S.(*uuid.UUID)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Question.
// This includes values selected through modifiers, order, etc.
func (_m *Question) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryQuiz queries the "quiz" edge of the Question entity.
func (_m *Question) QueryQuiz() *QuizQuery {
	return NewQuestionClient(_m.config).QueryQuiz(_m)
}

// QueryAnswers queries the "answers" edge of the Question entity.
func (_m *Question) QueryAnswers() *AnswerQuery {
	return NewQuestionClient(_m.config).QueryAnswers(_m)
}

// QueryAttemptAnswers queries the "attempt_answers" edge of the Question entity.
func (_m *Question) QueryAttemptAnswers() *AttemptAnswerQuery {
	return NewQuestionClient(_m.config).QueryAttemptAnswers(_m)
}

// Update returns a builder for updating this Question.
// Note that you need to call Question.Unwrap() before calling this method if this Question
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Question) Update() *QuestionUpdateOne {
	return NewQuestionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Question entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Question) Unwrap() *Question {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Question is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Question) String() string {
	var builder strings.Builder
	builder.WriteString("Question(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("text=")
	builder.WriteString(_m.Text)
	builder.WriteString(", ")
	builder.WriteString("order_index=")
	builder.WriteString(fmt.Sprintf("%v", _m.OrderIndex))
	builder.WriteByte(')')
	return builder.String()
}

// Questions is a parsable slice of Question.
type Questions []*Question
