// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"encore.app/ent/quiz"
	"encore.app/ent/user"
	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// Quiz is the model entity for the Quiz schema.
type Quiz struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Title holds the value of the "title" field.
	Title string `json:"title,omitempty"`
	// IsPublished holds the value of the "is_published" field.
	IsPublished bool `json:"is_published,omitempty"`
	// PassThreshold holds the value of the "pass_threshold" field.
	PassThreshold int `json:"pass_threshold,omitempty"`
	// OneAttempt holds the value of the "one_attempt" field.
	OneAttempt bool `json:"one_attempt,omitempty"`
	// ShowAnswers holds the value of the "show_answers" field.
	ShowAnswers bool `json:"show_answers,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the QuizQuery when eager-loading is set.
	Edges        QuizEdges `json:"edges"`
	user_quizzes *uuid.UUID
	selectValues sql.SelectValues
}

// QuizEdges holds the relations/edges for other nodes in the graph.
type QuizEdges struct {
	// CreatedBy holds the value of the created_by edge.
	CreatedBy *User `json:"created_by,omitempty"`
	// Questions holds the value of the questions edge.
	Questions []*Question `json:"questions,omitempty"`
	// Attempts holds the value of the attempts edge.
	Attempts []*Attempt `json:"attempts,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// CreatedByOrErr returns the CreatedBy value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e QuizEdges) CreatedByOrErr() (*User, error) {
	if e.CreatedBy != nil {
		return e.CreatedBy, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "created_by"}
}

// QuestionsOrErr returns the Questions value or an error if the edge
// was not loaded in eager-loading.
func (e QuizEdges) QuestionsOrErr() ([]*Question, error) {
	if e.loadedTypes[1] {
		return e.Questions, nil
	}
	return nil, &NotLoadedError{edge: "questions"}
}

// AttemptsOrErr returns the Attempts value or an error if the edge
// was not loaded in eager-loading.
func (e QuizEdges) AttemptsOrErr() ([]*Attempt, error) {
	if e.loadedTypes[2] {
		return e.Attempts, nil
	}
	return nil, &NotLoadedError{edge: "attempts"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Quiz) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case quiz.FieldIsPublished, quiz.FieldOneAttempt, quiz.FieldShowAnswers:
			values[i] = new(sql.NullBool)
		case quiz.FieldPassThreshold:
			values[i] = new(sql.NullInt64)
		case quiz.FieldTitle:
			values[i] = new(sql.NullString)
		case quiz.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case quiz.FieldID:
			values[i] = new(uuid.UUID)
		case quiz.ForeignKeys[0]: // user_quizzes
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Quiz fields.
func (_m *Quiz) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case quiz.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case quiz.FieldTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value.Valid {
				_m.Title = value.String
			}
		case quiz.FieldIsPublished:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_published", values[i])
			} else if value.Valid {
				_m.IsPublished = value.Bool
			}
		case quiz.FieldPassThreshold:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field pass_threshold", values[i])
			} else if value.Valid {
				_m.PassThreshold = int(value.Int64)
			}
		case quiz.FieldOneAttempt:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field one_attempt", values[i])
			} else if value.Valid {
				_m.OneAttempt = value.Bool
			}
		case quiz.FieldShowAnswers:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field show_answers", values[i])
			} else if value.Valid {
				_m.ShowAnswers = value.Bool
			}
		case quiz.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case quiz.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field user_quizzes", values[i])
			} else if value.Valid {
				_m.user_quizzes = new(uuid.UUID)
				*_m.user_quizzes = *value.S.(*uuid.UUID)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Quiz.
// This includes values selected through modifiers, order, etc.
func (_m *Quiz) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryCreatedBy queries the "created_by" edge of the Quiz entity.
func (_m *Quiz) QueryCreatedBy() *UserQuery {
	return NewQuizClient(_m.config).QueryCreatedBy(_m)
}

// QueryQuestions queries the "questions" edge of the Quiz entity.
func (_m *Quiz) QueryQuestions() *QuestionQuery {
	return NewQuizClient(_m.config).QueryQuestions(_m)
}

// QueryAttempts queries the "attempts" edge of the Quiz entity.
func (_m *Quiz) QueryAttempts() *AttemptQuery {
	return NewQuizClient(_m.config).QueryAttempts(_m)
}

// Update returns a builder for updating this Quiz.
// Note that you need to call Quiz.Unwrap() before calling this method if this Quiz
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Quiz) Update() *QuizUpdateOne {
	return NewQuizClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Quiz entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Quiz) Unwrap() *Quiz {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Quiz is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Quiz) String() string {
	var builder strings.Builder
	builder.WriteString("Quiz(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("title=")
	builder.WriteString(_m.Title)
	builder.WriteString(", ")
	builder.WriteString("is_published=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsPublished))
	builder.WriteString(", ")
	builder.WriteString("pass_threshold=")
	builder.WriteString(fmt.Sprintf("%v", _m.PassThreshold))
	builder.WriteString(", ")
	builder.WriteString("one_attempt=")
	builder.WriteString(fmt.Sprintf("%v", _m.OneAttempt))
	builder.WriteString(", ")
	builder.WriteString("show_answers=")
	builder.WriteString(fmt.Sprintf("%v", _m.ShowAnswers))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Quizs is a parsable slice of Quiz.
type Quizs []*Quiz
