// +build tools
// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encore.app/ent/answer"
	"encore.app/ent/attempt"
	"encore.app/ent/attemptanswer"
	"encore.app/ent/question"
	"encore.app/ent/quiz"
	"encore.app/ent/schema"
	"encore.app/ent/user"
	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	answerFields := schema.Answer{}.Fields()
	_ = answerFields
	// answerDescIsCorrect is the schema descriptor for is_correct field.
	answerDescIsCorrect := answerFields[2].Descriptor()
	// answer.DefaultIsCorrect holds the default value on creation for the is_correct field.
	answer.DefaultIsCorrect = answerDescIsCorrect.Default.(bool)
	// answerDescOrderIndex is the schema descriptor for order_index field.
	answerDescOrderIndex := answerFields[3].Descriptor()
	// answer.DefaultOrderIndex holds the default value on creation for the order_index field.
	answer.DefaultOrderIndex = answerDescOrderIndex.Default.(int)
	// answerDescID is the schema descriptor for id field.
	answerDescID := answerFields[0].Descriptor()
	// answer.DefaultID holds the default value on creation for the id field.
	answer.DefaultID = answerDescID.Default.(func() uuid.UUID)
	attemptFields := schema.Attempt{}.Fields()
	_ = attemptFields
	// attemptDescID is the schema descriptor for id field.
	attemptDescID := attemptFields[0].Descriptor()
	// attempt.DefaultID holds the default value on creation for the id field.
	attempt.DefaultID = attemptDescID.Default.(func() uuid.UUID)
	attemptanswerFields := schema.AttemptAnswer{}.Fields()
	_ = attemptanswerFields
	// attemptanswerDescID is the schema descriptor for id field.
	attemptanswerDescID := attemptanswerFields[0].Descriptor()
	// attemptanswer.DefaultID holds the default value on creation for the id field.
	attemptanswer.DefaultID = attemptanswerDescID.Default.(func() uuid.UUID)
	questionFields := schema.Question{}.Fields()
	_ = questionFields
	// questionDescOrderIndex is the schema descriptor for order_index field.
	questionDescOrderIndex := questionFields[2].Descriptor()
	// question.DefaultOrderIndex holds the default value on creation for the order_index field.
	question.DefaultOrderIndex = questionDescOrderIndex.Default.(int)
	// questionDescID is the schema descriptor for id field.
	questionDescID := questionFields[0].Descriptor()
	// question.DefaultID holds the default value on creation for the id field.
	question.DefaultID = questionDescID.Default.(func() uuid.UUID)
	quizFields := schema.Quiz{}.Fields()
	_ = quizFields
	// quizDescIsPublished is the schema descriptor for is_published field.
	quizDescIsPublished := quizFields[2].Descriptor()
	// quiz.DefaultIsPublished holds the default value on creation for the is_published field.
	quiz.DefaultIsPublished = quizDescIsPublished.Default.(bool)
	// quizDescPassThreshold is the schema descriptor for pass_threshold field.
	quizDescPassThreshold := quizFields[3].Descriptor()
	// quiz.DefaultPassThreshold holds the default value on creation for the pass_threshold field.
	quiz.DefaultPassThreshold = quizDescPassThreshold.Default.(int)
	// quizDescOneAttempt is the schema descriptor for one_attempt field.
	quizDescOneAttempt := quizFields[4].Descriptor()
	// quiz.DefaultOneAttempt holds the default value on creation for the one_attempt field.
	quiz.DefaultOneAttempt = quizDescOneAttempt.Default.(bool)
	// quizDescShowAnswers is the schema descriptor for show_answers field.
	quizDescShowAnswers := quizFields[5].Descriptor()
	// quiz.DefaultShowAnswers holds the default value on creation for the show_answers field.
	quiz.DefaultShowAnswers = quizDescShowAnswers.Default.(bool)
	// quizDescID is the schema descriptor for id field.
	quizDescID := quizFields[0].Descriptor()
	// quiz.DefaultID holds the default value on creation for the id field.
	quiz.DefaultID = quizDescID.Default.(func() uuid.UUID)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescRole is the schema descriptor for role field.
	userDescRole := userFields[3].Descriptor()
	// user.DefaultRole holds the default value on creation for the role field.
	user.DefaultRole = userDescRole.Default.(string)
	// userDescID is the schema descriptor for id field.
	userDescID := userFields[0].Descriptor()
	// user.DefaultID holds the default value on creation for the id field.
	user.DefaultID = userDescID.Default.(func() uuid.UUID)
}
